### ISSUE TITLE
Key generation does not write to the specified location

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#1]
1. 

``` sh
rnpkeys --generate-key --homedir=/tmp
```
Writes to:
```
# rnp: generated keys in directory /tmp/f0d9c5614f47f4f6
ls 
```

2.
``` sh
rnppkeys --generate-key --keyring=/tmp/x.gpg
```
Writes to:
```
rnp: generated keys in directory /${HOME}/.gnupg/b6d281342b971964
```

**Comment by shaunwheelhouse** [comment]
I'll look into this now, it's important that we have deterministic key directories for testing. 🔧

**Comment by ronaldtse** [comment]
@shaunwheelhouse I think we need to clean up key location functionality in general, and `--homedir` feels confusing to me.

Maybe instead of `--homedir` and `--keyring`, we could have something like:

* `--keyring` that points directly at a keyring file
* `--keyring-dir` that points to a directory that contains keyrings (e.g., by default it generates `pubring.gpg` and `secring.gpg`)

The option names obviously could definitely be improved.

What do you think?

**Comment by shaunwheelhouse** [comment]
I think that's far more intuitive, we should make the change. 👍

**Comment by ronaldtse** [comment]
A second thought: maybe for `netpgpkeys` we don't even need these options, but we can simply assume that the argument without `--` prefix is the keyring location?

Adds a key to the specified keyring, or creates it:
```
netpgpkeys --generate-key [keyring-location]
```

Adds a key to `secring.gpg` keyring in `keyring-dir`:
```
netpgpkeys --generate-key [keyring-dir]
```

And by default `keyring-dir=${HOME}/.gnupg`?

**Comment by shaunwheelhouse** [comment]
That does have a much less "frameworked" feel to me which I think is good for utilities like this. Sane defaults with easy and predictable overrides. I like it. It might be worth considering adding a `-d/--directory` switch though to prevent accidental mistakes.

**Comment by ronaldtse** [comment]
Agree @shaunwheelhouse . Let's do it this way then.

**Comment by shaunwheelhouse** [comment]
@ronaldtse Sounds good. In the interim I have a temporary fix that should at least get it behaving predictably for you.

**Comment by frank-trampe** [comment]
I got completely different behavior on d7d4f12e9d8464280e61153eafe3f017468e4d9b. `./rnpkeys --generate-key --userid=packaging@ribose.com --homedir=/root/.tmp/` put `pubring.gpg` and `secring.gpg` in `/root/.tmp/.rnp`. This is also undesirable behavior, because the same option in gpg specifies the gpg configuration directory (usually `~/.gnupg`), not the user's home directory. This makes it very difficult to interoperate on the same set of keys.

**Comment by ronaldtse** [comment]
@frank-trampe I think the option to specify the key directory is now called 'keydir'?

**Comment by dewyatt** [comment]
I think that this is generally resolved. Please re-open if not, but it looks right to me.
