### ISSUE TITLE
Heavily DRY out codebase

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#10]
Some of the executables are compiled on duplicated code in the codebase. For example, `netpgpverify` has its own copy of `libverify.c` but there is another one in `libverify`.

All executables should utilize a single copy of common code.

**Comment by ni4** [comment]
Do we really need libverify? As I understand it's goal is to have small/lightweight non-dependent of anything library which allows to check signatures.

**Comment by ronaldtse** [comment]
We should get rid of libverify-- I don't think it's necessary to have a separate verification lib separate from the signing functions.

**Comment by ni4** [comment]
@ronaldtse Since we do not have libverify for a while, and almost all old codebase is removed shouldn't we close this?

**Comment by ronaldtse** [comment]
Agree. Thanks @ni4!
