### ISSUE TITLE
Cleanup `tst` directory, move possible tests into cmocka, integrate into test flow

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#103]
The `/tst` directory contains a number of tests (and some unnecessary files) that are not utilized in the test flow.

This task is to:

* move/rewrite valid tests from `tst` into the cmocka framework under `src/cmocka`
* rewrite/formalize command line tests in the CI test flow, for example, using [BATS](https://github.com/sstephenson/bats)
* remove unnecessary files from the `tst` directory and get rid of the directory itself

**Comment by ni4** [comment]
I will fix this issue as the part of #294 - tests from this directory will be re-implemented in python and old ones will be removed.

**Comment by ni4** [comment]
@ronaldtse Since we have python CLI tests probably it's time to remove tst directory? Or do we have any specific need for that?

**Comment by ronaldtse** [comment]
We've been wanting to remove `tst` forever. Could you verify that all `tst` tests have their equivalents in the CLI tests, and remove the directory? Thanks!

**Comment by ni4** [comment]
Ok! Will add missing tests if any and close this issue.

**Comment by ronaldtse** [comment]
@ni4 @dewyatt can we close this? Thanks!

**Comment by ni4** [comment]
@ronaldtse Yeah, it can be closed - we got rid of `tst` directory at some point.

**Comment by ronaldtse** [comment]
Thanks @ni4 for the confirmation!
