### ISSUE TITLE
rnp --clearsign generates an ASCII-armored .gpg

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#104]
`rnp --clearsign inputfile` will generate an ASCII-armored file named inputfile.gpg, but this is misleading as typically ASCII-armored content is named `.asc`.
`rnp --clearsign --armor inputfile` will generate the same content, but with the correct `.asc` name instead.

`gpg --clearsign inputfile` generates inputfile.asc so we should probably align with that behavior.

**Comment by ni4** [comment]
Issue is fixed together with other stuff in 1e5df364260f2b7795935e161110736b16d9eb85
