### ISSUE TITLE
See if we can make hash handling a bit more consistent and improve related tests

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#106]
Related discussion in https://github.com/riboseinc/rnp/pull/96

It looks like there are a few different places that deal with hashes that are a bit scattered around.
I wonder if we can improve this:

* `pgp_is_hash_alg_supported`
* `pgp_hash_any`
* `pgp_str_to_hash_alg`

Additionally, with the current tests, there are a few errors that are printed out because these functions need updates, but the tests pass (probably by defaulting to a different algorithm):

* `pgp_hash_any: bad algorithm` (`pgp_hash_any`)
* `Ignoring unknown hash algo 'RIPEMD160'` (`pgp_str_to_hash_alg`)
* `Ignoring unknown hash algo 'SHA224'` (`pgp_str_to_hash_alg`)

**Comment by ronaldtse** [comment]
Fully agree with @dewyatt . I'm hoping that we can consolidate all these in a separate file per hash algorithm.

**Comment by ronaldtse** [comment]
@randombit will be working on this. Would be great if we can make it much simpler to add hash algorithms with a single touch point. Thanks!

**Comment by randombit** [comment]
Think this is done with #135 - adding a new hash now requires just modifying `hash.h` to add the codepoint and `hash.c` to modify a couple of lookup tables.

**Comment by ronaldtse** [comment]
Thanks @randombit !
