### ISSUE TITLE
RFC 4880 bis-01: Support EdDSA

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#109]
We should support EdDSA, originally defined in [draft-koch-eddsa-for-openpgp-04](https://tools.ietf.org/html/draft-koch-eddsa-for-openpgp-04) and now included in [RFC 4880 bis-01](https://tools.ietf.org/html/draft-ietf-openpgp-rfc4880bis-01).

This work is to implement support for:
* Public key algorithm: 22 (EdDSA)
* Ed25519 curve

**Comment by ronaldtse** [comment]
EdDSA support relies on enhancing Botan with Ed25519 support.

Existing Ed25519 implementations can be found:
  * https://github.com/floodyberry/ed25519-donna
  * https://github.com/orlp/ed25519

**Comment by randombit** [comment]
Addition of Ed25519 to Botan would be great.

https://github.com/orlp/ed25519 has zlib license which is not compatible with BSD-2, no go

Floodyberry's Ed25519 is (IIRC) public domain so ok, but we wouldn't want to take all of his versions. Just use the 64-bit impl (curve25519-donna-64bit.h, modm-donna-64bit.h) and use either a native uint128_t or the `donna128` 128-bit integer type (this is how we do X25519). It leaves some performance on the table but simplifies implementation/testing/maintenence.

Another implementation (one I planned to use) was the public domain code in SUPERCOP (http://bench.cr.yp.to/supercop.html) either `crypto_sign/ed25519/ref` or `crypto_sign/ed25519/ref10`.

Any 3 of these would require some substantial modifications to be acceptable to upstream, `ref` is probably the easiest (though `ref` is much slower than `ref10` - http://bench.cr.yp.to/impl-sign/ed25519.html)

**Comment by ronaldtse** [comment]
@randombit Thank you for the detailed info. SUPERCOP's `ref10` does seem more complex than `ref`...

Let's see who's free to work on this!

**Comment by flowher** [comment]
Hi guys, I'm definitely planning to implement this after coming back from vacation.

**Comment by ronaldtse** [comment]
This enhancement is apparently of interest to many. @randombit probably will be adding EdDSA to botan. @flowher perhaps you can work with @randombit on this?

**Comment by flowher** [comment]
ok

**Comment by randombit** [comment]
@flowher Did you have plans to start on this shortly? I can work on EdDSA in Botan starting first week in June, and then you can handle the rnp side after. Or if you planned to get to this earlier and want to take on also adding EdDSA to Botan, then I can just limit myself to reviewing changes and work on SM2 instead. Let me know.

**Comment by flowher** [comment]
@randombit I would say go ahead with EdDSA implementation. I'm changing rnp so that it supports ECDSA and ECDH. There is some work needed in both - rnp frontend (rnp, rnpkey - this supports only RSA) and backend for EC. So it will take me some time.
I think this work will be useful also for EdDSA, so I can handle rnp side after it is available in Botan (if needed). 
Plus - I like idea to base the EdDSA on code from SUPERCOP/NaCl/DJB implementation

**Comment by ronaldtse** [comment]
Got it. It's all yours @randombit !

**Comment by randombit** [comment]
Done with #200
