### ISSUE TITLE
Overflow in write_seckey_body

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#111]
I was playing with clang's sanitizers and confirmed an issue here:
https://github.com/riboseinc/rnp/blob/f20e993e7b7e9e11e70f9b71f1db2b005746454c/src/lib/create.c#L434
We're calculating a SHA1 hash but we're using the hash size of `key->hash_alg` to determine the size of the buffer we allocate.
So this overflows in the tests when `key->hash_alg` is something that would produce a digest smaller than SHA1, like MD5.

It's not immediately clear to me what the best fix is here so I'm just documenting it.

**Comment by ronaldtse** [comment]
It seems that this function is pretty much hardcoded SHA1 and CAST, we should probably support different digest and symmetric algorithms properly here.

**Comment by randombit** [comment]
I believe this was fixed by #140

**Comment by dewyatt** [comment]
As mentioned, this should be fixed now, closing.
