### ISSUE TITLE
Incorrect block cipher free

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#112]
https://github.com/riboseinc/rnp/blob/f20e993e7b7e9e11e70f9b71f1db2b005746454c/src/lib/symmetric.c#L103

I think we should be using `botan_block_cipher_destroy` here.

We should probably also NULL this after the free here:
https://github.com/riboseinc/rnp/blob/f20e993e7b7e9e11e70f9b71f1db2b005746454c/src/lib/symmetric.c#L113

**Comment by ronaldtse** [comment]
@randombit could you please have a look here? You're probably most familiar with this section. Thanks!

**Comment by randombit** [comment]
@ronaldtse Will look at this today

**Comment by randombit** [comment]
Fixed!
