### ISSUE TITLE
Calling rnp_load_keys more than once will leak keyrings

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#115]
`load_keys_ssh` actually appears to append to the existing keyrings in memory.
`load_keys_gnupg` just overwrites (and leaks) it: https://github.com/riboseinc/rnp/blob/728150f5b2d83a8508885f204b050e3e9a67e695/src/lib/rnp.c#L1053

We should determine whether calling rnp_load_keys should append to the existing in-memory keyrings, or not. Either way, we should not leak them.

**Comment by ni4** [comment]
Both `load_keys_ssh` and `load_keys_ssh` were removed long time ago.
And it doesn't seem that current codebase exposes such leaks. So closing this.
