### ISSUE TITLE
pgp_push_enc_crypt leak

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#116]
Maybe low priority, but just documenting for later:

https://github.com/riboseinc/rnp/blob/2d21450e8f5601da0f203507966c3a7308469bd3/src/lib/writer.c

free_crypt is always 0 so the crypt object will never be freed.
Plus the `free` call should actually probably be something like `pgp_encrypt->crypt->decrypt_finish(pgp_encrypt->crypt);`.

In `write_seckey_body`, for example, we allocate a crypt object and pass it in:
https://github.com/riboseinc/rnp/blob/2d21450e8f5601da0f203507966c3a7308469bd3/src/lib/create.c#L505

`write_seckey_body` never calls `decrypt_finish` (which we should probably rename to `finish`) and the writer won't call it either.
We should look at how `pgp_push_enc_crypt` is currently used and document the responsibility for freeing.

**Comment by ni4** [comment]
Not an issue anymore since `pgp_push_enc_crypt` was replaced with newer functions which don't seem to have any memory leaks.
