### ISSUE TITLE
Clean up unused files

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#12]
The repo is littered with unused files such as:
* presentation files
* files containing TODOs
* unused libraries

**Comment by zgyarmati** [comment]
Mostly fixed with eaaa2ca, 
but i wasn't sure about the following scipts, so left them in for now:
 remove_artifacts.sh (git clean -dfx works better imho)
 docker.sh (is it used somewhere, in CI for example?)
 Licence || LICENSE.md (will be fixed with #41)

Anything else i missed?

**Comment by ronaldtse** [comment]
We previously used `remove_artifacts.sh` just to remove build artifacts for packaging and probably don't need it anymore. There should be a `make clean` command that does `git clean -dfx`.

`docker.sh` is used to start a CentOS container for RPM packaging. Maybe we should put this in the `packaging/redhat/extra` directory?

**Comment by ronaldtse** [comment]
`License` has been merged into `LICENSE.md` now.
