### ISSUE TITLE
pgp_sign_buf and pgp_sign_file should fail when cleartext=1 and armored=0

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#121]
We should check the RFC and confirm, but I believe a cleartext signature is, by definition, armored.
See also discussion here: https://github.com/riboseinc/rnp/pull/96

**Comment by ni4** [comment]
I'm closing this since `pgp_sign_buf` and `pgp_sign_file` were superceded by streamed approach, where this problem doesn't happen.
