### ISSUE TITLE
Support SM2 

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#127]
SM2 is a family of elliptic curve algorithms described in [draft-shen-sm2-ecdsa-02](https://tools.ietf.org/html/draft-shen-sm2-ecdsa-02), and includes ECDSA and public key encryption algorithms.

This task is to implement support for SM2 in rnp (and in conjunction with SM3), and depends on implementation of SM2 within Botan.

Relevant OIDs (http://gmssl.org/docs/oid.html):

* 1.2.156.10197.1.301, SM2 Elliptic Curve Cryptography
* 1.2.156.10197.1.301.1, SM2-1 Digital Siganture Algorithm
* 1.2.156.10197.1.301.2, SM2-2 Key Exchange Protocol
* 1.2.156.10197.1.301.3, SM2-3 Public Key Encryption
* 1.2.156.10197.1.501, SM2 Signing with SM3
* 1.2.156.10197.6.1.1.3, SM2 Standard

**Comment by ronaldtse** [comment]
The best public information I was able to find is this link:
http://blog.csdn.net/arlaichin/article/details/23708155

**Comment by ronaldtse** [comment]
I believe this is completed, right @randombit ? Or is this not selectable from the CLI on key generation?

**Comment by randombit** [comment]
@ronaldtse Encryption is not supported yet, PR for that coming today I think

**Comment by ronaldtse** [comment]
@randombit should we close this?

Ref: https://github.com/riboseinc/rfc-openpgp-oscca/pull/2

**Comment by ronaldtse** [comment]
@randombit can we close this now?

**Comment by randombit** [comment]
@ronaldtse I believe everything is done here but let me double check.

**Comment by ronaldtse** [comment]
Thanks @randombit !
