### ISSUE TITLE
Add support for SM3+RSA signatures

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#129]
This should allow utilizing SM3 for the entire flow of [OpenPGP](https://tools.ietf.org/html/rfc4880) except for:
* 5.13 and 5.14 which hard-codes the SHA-1 algorithm for checksums
* v4 fingerprinting that requires SHA-1

Relevant OID from [GmSSL](http://gmssl.org/docs/oid.html):
* 1.2.156.10197.1.504 RSA Signing with SM3

**Comment by randombit** [comment]
I believe this already works.

**Comment by ronaldtse** [comment]
I wasn't aware that we could already write the above OID (RSA+SM3) in the signature packet?

**Comment by randombit** [comment]
Yes I added the SM3 OIDs to Botan already, so asking for a RSA+SM3 signature just works (this is tested in one of the cmocka tests). I just looked over RFC 4880 a bit to make sure there isn't something else we need to do, but if so I didn't notice it.

**Comment by ronaldtse** [comment]
Aha! Silly me, I do see that the SM3 combinations are already included in botan's `oids.cpp`!
