### ISSUE TITLE
EC key generation

### ISSUE THREAD

**Issue by flowher** [riboseinc/rnp#130]
Currently frontend for key generation ``rnpkeys`` supports only RSA key generation. Goal of this ticket is to implement support for generation of ECDSA and ECDH keys. 
It is first step towards implementation support for both algorithms.

**Comment by ronaldtse** [comment]
Very nice first step indeed. Welcome back @flowher !

**Comment by flowher** [comment]
Following comment from #200 should be taken into account:

"
Currently keygen works by requesting a 255 bit key. It would be nice to clean this up by adding an algorithm identifier to rnp_generate_key. The underlying API pgp_generate_keypair does take an alg id now.
"

**Comment by ronaldtse** [comment]
Ah @flowher I found this from your comment in #207 . Are you planning to include this in #207 or do you plan to have a separate one for exposing key generation?

**Comment by flowher** [comment]
Actually #207 and this one will be separated
#207 is strictly about supporting ECDSA and this one is about changes to rnpkeys (like see the comment above)
