### ISSUE TITLE
Key generation support with key flags and subkeys

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#136]
As GnuPG users expect we should support key generation using different key flags and allow generation of multiple subkeys.

Here's a good example:
https://www.gnupg.org/documentation/manuals/gnupg/Unattended-GPG-key-generation.html

**Comment by ni4** [comment]
Important thing to note here is that RSA key pair by default should have sign-only main key and encrypting subkey.

**Comment by dewyatt** [comment]
I've ended up doing a bit of work on this as it relates to the other pieces I'm currently working on and will help me validate some things as well.

The coming PR (probably will be a few days still) is going to be very large and noisy, but should add a lot of vital functionality (and organize things a bit). I'm just focusing on the core, not the CLI or unattended stuff, just the basic plumbing.

**Comment by ronaldtse** [comment]
Thanks @dewyatt !

**Comment by dewyatt** [comment]
Let's call this done, though there's probably some minor plumbing we'll want to add for creating additional subkeys and such.
