### ISSUE TITLE
Support SM4 for symmetric encryption

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#137]
SM4 is defined in the "GM/T 0002-2012 SM4 Block Cipher Algorithm Standard" document and details of it can be found [here](https://tinycrypt.wordpress.com/2017/02/15/asmcodes-sm4/).

SM4 has been adopted in TPM 2.0 of the Trust Computing Group (TCG) standard.

**Comment by ronaldtse** [comment]
I believe this is completed, right @randombit ? Or is this not selectable from the CLI on key generation?

**Comment by randombit** [comment]
This is completed with #222. Passing `--cipher=sm4` to `rnpkeys` during keygen should set the cipher appropriately just like any other.
