### ISSUE TITLE
No way to export a private key

### ISSUE THREAD

**Issue by randombit** [riboseinc/rnp#141]
Wanted the generate a key with rnp and read it with gpg to test #140, but it doesn't seem `rnpkeys` or any API exposed in `rnp.h` supports this operation - `rnp_export_key` only handles public keys.

**Comment by dewyatt** [comment]
Good point, we need a `rnp_export_secret_key`, and all the connective pieces for rnpkeys.

**Comment by flowher** [comment]
There is also no way to export key with subkeys
