### ISSUE TITLE
Create list of officially-supported platforms

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#152]
As per our discussion @zgyarmati and @catap , let's come up with a list of officially supported platforms.

Let me start with:
* RHEL/CentOS 7
* Fedora 25

**Comment by zgyarmati** [comment]
Ubuntu 16.04 LTS
Ubuntu 17.04   
Debian 8
Debian 9 (from middle of June, the planned rls date is 17th)

**Comment by zgyarmati** [comment]
OpenSuse maybe?
 And a bit later (when the main server/desktop distros are covered) i also would like to create a package for Buildroot (https://buildroot.org/) and OpenWrt/LEDE, which will show eventually if there are any issues with cross-compilation and on different HW platforms.

**Comment by catap** [comment]
also Ubuntu 14.04 LTS because it's still alive.

Yes for OpenSUSE and SLES

**Comment by ronaldtse** [comment]
Closed with #174 .
