### ISSUE TITLE
Remove pgp_io_t usage

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#157]
The usage of `pgp_io_t` is deemed unnecessary (as discussed with @catap and @dewyatt ) and should be replaced with normal `stdout`/`stderr`.

We should replace all instances with the normal approach.

**Comment by ni4** [comment]
As I'm working on the refactoring now I can cut it out. However, my opinion is that we should move all error reporting/writing to stdout to some method calls with rnp_t parameter - so later on we can easily redirect output later if needed. @ronaldtse, what do you think?

**Comment by catap** [comment]
I see two way:
 - use something likes `set_pass_fd` to error stream;
 - add a standard variable `rnp_errno` and implement a function that convert rnp error to human-related error.

I vote for last one because it's more common and this way is used for example [OpenSSL](https://wiki.openssl.org/index.php/Manual:ERR_error_string(3))

**Comment by ni4** [comment]
Sure, rnp_errno can be added as well so upper layers can see what happened below. What I mean is that we should set errors via some single function call, i.e. rnp_error(int code, char *msg, ...), so later on it would be easier to change the way errors are reported. Within the current implementation we need to go through the all code and seek for printf's and so on.

**Comment by catap** [comment]
@ni4 I saw in code `PGP_ERROR_1` that looks like this sort of function.

But I mean another idea. We can keep a error code status inside `rnp_t` or `rnp_ctx_t`, and made a big table where we assigned for each possible error string an error code and the function that returns this error string, if user required it.

Likes `errno` and `strerror` or how [OpenSSL](https://wiki.openssl.org/index.php/Manual:ERR_error_string(3)) works with error.

**Comment by dewyatt** [comment]
@catap See `src/lib/misc.c` `pgp_errcode`.
Also, the reader/writer framework keeps a linked list of errors, which is what `PGP_ERROR_1` deals with (also see `pgp_stream_t->errors`).

@ni4 If you were to add an `rnp_t` parameter to every function that calls `fprintf(stderr, ...)`, I think we would be tightly coupling things and losing a layer of abstraction that we may need later.

Generally, I think that https://github.com/riboseinc/rnp/issues/153 is likely to help with some of this.

**Comment by catap** [comment]
@dewyatt sorry, I missed it.

Yeah, I mean `pgp_errcode` and existed code :)

**Comment by ni4** [comment]
I see it. I agree with this idea, however this makes sense for 'predictable' errors, and errors which may have or require further interpretation - like, wrong keyring file, unsupported algorithm, too low RSA exponent bitcount and so on. But we also have printf's which output additional, mostly debug information which mostly is a result of unexpected behavior. In this case only logging of these messages makes sense - we just will not have time to assign new error code for each of those printfs.

**Comment by ni4** [comment]
@dewyatt somehow GitHub didn't refresh the story before my reply. Agree with you - I forgot that there is a set of functions which will not have access to rnp_t. So anyway we'll have some code which printf'ing to the stderr/stdout.

**Comment by catap** [comment]
@ni4 I may wrong but I think that debug errors should write to stderr and the way to redirect it to custom stream is overengineering.

**Comment by ni4** [comment]
Yep, maybe I'm just overcomplicating things :)

**Comment by ronaldtse** [comment]
@ni4 I agree that instead of directly writing to `stdout`/`strerr` or `printf`, we should have an abstract layer with a custom structure for output, like riboseinc/retrace#143 .

Directly writing to `stderr` seems a bit too tight in coupling -- some messages are informative ones that do not affect functionality and we don't need to clutter the user's output unless required. Maybe we should have a `--verbose` option.

**Comment by ni4** [comment]
@ronaldtse We have --verbose (-v) option now, which allows to raise verbosity layer. However it doesn't seem to be used anywhere.

**Comment by ronaldtse** [comment]
Yes @ni4 we should fix that.

**Comment by catap** [comment]
One more point from #264 discussion:

> Ok, about `pgp_io_t` and streams. I think we should change the API and provides the way to setup callbacks for interactive interaction with user.
> By default we should use current logic with read from `stdio`, but we should provide a way to setup callbacks. And first user of new callback will be our tests :)
