### ISSUE TITLE
Review calls to `rnp_strdup`

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#160]
As discussed in #159, we should review all calls to `rnp_strdup` (which is actually a copy of `strdup`) to make sure they are acting on NULL-terminated strings instead of a `pgp_memory_t` buffer.

With only 16 calls as of now, since this function easily hides memory allocation, the preference is to get rid of it...

**Comment by ni4** [comment]
@ronaldtse Now it is called only on NULL-strings, and actually is called only in a few places compared to `strdup()`. So should I remove those calls? There are some arguments against that it is not a part of standard, but part of POSIX.

**Comment by ronaldtse** [comment]
If `rnp_strdup` is no longer necessary, let's remove those calls, one less function to worry about. Thoughts @dewyatt ?

**Comment by dewyatt** [comment]
Yeah it seems good to remove it, given that we're already using `strdup` a bunch.
