### ISSUE TITLE
pass-fd usage is broken, tests are not communicating passphrases correctly

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#171]
It looks like 4 or so tests are succeeding but probably should *not* be.
Essentially, we're probably generating keys without a passphrase (and signing/decrypting, etc), even when we *think* we're using a passphrase.

While coming up with a fix, I realized there is actually a relevant fix upstream (and a few others). I'll create a separate issue to evaluate and pull in upstream changes.

Anyhow, I suspect there are multiple issues here:
* Some of the tests are calling `setupPassphrasefd` once, which writes the passphrase once, and then they loop and call multiple things that require a passphrase. So that's one issue - the passphrase has to be written to the pipe before each call that would require a passphrase.
* Secondly, calling `setupPassphrasefd`+`rnp_setvar` is only a valid thing to do *before* calling `rnp_init`. The `fdopen` call is only made in `rnp_init`, IIRC. After that, `pass-fd` doesn't matter (`rnp->passfp` does).
* I think 6b1cbb0925e5962188ebc1facfb4f963a7c2c961 and https://github.com/riboseinc/rnp/commit/594dd010f02233a4dc0a65518016f074915446d9#diff-675d74573e8c0ca275d41dd41e2a0a72 actually ended up covering up the underlying issue. (`fgets` reads up to `EOF` or `\n`, including `\n`. So sometimes we do need to truncate a character, sometimes we don't. `getpass` has code to do this internally.)
* At first glance I would also think that when `fgets()` fails in `find_passphrase`, we should be indicating an error to the caller (rather than saying "we read a passphrase of length 0"). I haven't looked at this much, it should be revisited after pulling in the upstream changes.

Related: #39

**Comment by MohitKumarAgniotri** [comment]
@dewyatt I will have a look at this one.

**Comment by ni4** [comment]
I fixed some testing/pass-fd issues in 2daa2c4 and ded5a07, however they are not merged to master yet.

**Comment by ni4** [comment]
I'm closing this since it was fixed in #258 or some of the previous PR.

**Comment by dewyatt** [comment]
This wasn't fixed, unfortunately, so reopening.

**Comment by dewyatt** [comment]
Nevermind, the issues I'm seeing are of a slightly different form from this, so closing again.
I think it's just the `ask_expert_details` tests, since they don't write any passphrases.
But since I started a bit of work on https://github.com/riboseinc/rnp/issues/39 again, it may be better to handle things there.
