### ISSUE TITLE
Upstream changes

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#172]
There are half a dozen or so changes in upstream CVS that we need to evaluate and merge.
They should likely be evaluated individually. I saw one that was basically the exact fix I was going to do for #171.

I'm going to be away for about a week, but I can get to them then, if nobody else does.

**Comment by randombit** [comment]
@dewyatt Where is upstream? The only repo I was aware of is /src/crypto/external/bsd/netpgp/ in NetBSD CVS, which last had a checkin in 2014.

**Comment by dewyatt** [comment]
@randombit You're on the right track.
I haven't used CVS in probably 10 years so surely there's a better way, but here's a few links via cvsweb:

http://cvsweb.netbsd.org/bsdweb.cgi/src/crypto/external/bsd/netpgp/dist/src/lib/keyring.h?only_with_tag=MAIN
http://cvsweb.netbsd.org/bsdweb.cgi/src/crypto/external/bsd/netpgp/dist/src/lib/keyring.c?only_with_tag=MAIN
http://cvsweb.netbsd.org/bsdweb.cgi/src/crypto/external/bsd/netpgp/dist/src/lib/netpgp.c?only_with_tag=MAIN
http://cvsweb.netbsd.org/bsdweb.cgi/src/crypto/external/bsd/netpgp/dist/src/lib/reader.c?only_with_tag=MAIN
http://cvsweb.netbsd.org/bsdweb.cgi/src/crypto/external/bsd/netpgp/dist/src/lib/signature.c?only_with_tag=MAIN

**Comment by ronaldtse** [comment]
I've done a check on netpgp and these are the diffs we should merge (if still relevant):

* [netpgp.1](http://cvsweb.netbsd.org/bsdweb.cgi/src/crypto/external/bsd/netpgp/dist/src/netpgp/netpgp.1.diff?r1=1.19&r2=1.21&only_with_tag=MAIN)
* [keyring.h](http://cvsweb.netbsd.org/bsdweb.cgi/src/crypto/external/bsd/netpgp/dist/src/lib/keyring.h.diff?r1=1.32&r2=1.34&only_with_tag=MAIN)
* [keyring.c](http://cvsweb.netbsd.org/bsdweb.cgi/src/crypto/external/bsd/netpgp/dist/src/lib/keyring.c.diff?r1=1.50&r2=1.55&only_with_tag=MAIN)
* [netpgp.c](http://cvsweb.netbsd.org/bsdweb.cgi/src/crypto/external/bsd/netpgp/dist/src/lib/netpgp.c.diff?r1=1.98&r2=1.101&only_with_tag=MAIN)
* [reader.c](http://cvsweb.netbsd.org/bsdweb.cgi/src/crypto/external/bsd/netpgp/dist/src/lib/reader.c.diff?r1=1.49&r2=1.52&only_with_tag=MAIN)
* [signature.c](http://cvsweb.netbsd.org/bsdweb.cgi/src/crypto/external/bsd/netpgp/dist/src/lib/signature.c.diff?r1=1.34&r2=1.37&only_with_tag=MAIN)

**Comment by randombit** [comment]
Not sure why I don't see these commits in my local CVS checkout. *shrug* There is an up to date git mirror of NetBSD src at https://github.com/jsonn/src/tree/trunk/crypto/external/bsd/netpgp/dist/src/lib
