### ISSUE TITLE
librnp standalone

### ISSUE THREAD

**Issue by danghvu** [riboseinc/rnp#173]
Is there a document on how to build this library alone and/or using its APIs ?

**Comment by zgyarmati** [comment]
Dear Danghvu,

thanks for reaching out! Currently we are still doing an overhaul of the source tree and API changes are rather possible. Nevertheless you can compile&install the package on the autotools way, and you will have the librnp binary and the header files installed, next to the executables.
 ATM the best way to get an overview of the API is the librnp.3 man file, which is also installed if you install the lib, or you can see the troff file here:
https://github.com/riboseinc/rnp/blob/master/src/lib/librnp.3
In the meantime  i'm working on providing autobuilt .rpm/.deb packages, which will also contain the library packaged seperately from the executables, so stay tuned :)
If you think this comment answering your questions (at least for now), please go ahead and close it.

**Comment by danghvu** [comment]
Thanks
