### ISSUE TITLE
Support non-RSA public keys

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#18]
While it is technically supposed to support ElGamal, etc non-RSA algorithms, the code is now hard-coded to only use RSA.

This task is to complete support of non-RSA schemes.

**Comment by flowher** [comment]
@ronaldtse Should I use this record to implement ECDSA, ECDH and EDDSA ?
I've just started implementing support for ECDSA

**Comment by ronaldtse** [comment]
@flowher yes please, please go ahead here. Thanks!
