### ISSUE TITLE
Create test suite for executables

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#180]
From @dewyatt : 
> Test the executables in addition to the APIs. For example, we may construct a command line that executes "rnpkeys --homedir=... --generate-key" and then use file_exists to ensure the correct files were generated in the correct location, check the process exit code, etc. This would essentially test another layer of the code.

**Comment by ronaldtse** [comment]
@zgyarmati yes it's time to migrate that away. Many of the old `test`s pass even when the executables aren't built 😉 

There are also shell executable test frameworks like [BATS](https://github.com/sstephenson/bats) that could be considered.

**Comment by ronaldtse** [comment]
@frank-trampe this issue seems related to what you're doing too.

**Comment by ni4** [comment]
This is actually what I'm doing in #294.

**Comment by ni4** [comment]
I'm closing this since issue #294 is done and closed.
