### ISSUE TITLE
Key generation without passphrase should not fail silently

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#19]
Key generation via `rnp` command requires a passphrase, but there is no error when an empty passphrase is entered yet there is no key generated, which is confusing for people who use it as a `gpg` replacement.

We should allow generating keys with or without passphrase, and provide proper error messages if anything bad happens.

**Comment by frank-trampe** [comment]
I think that this specific bug has been fixed in master. I was able to generate a key without a passphrase and to encrypt and to decrypt with that key. But gpg is unable to use the resulting key.

**Comment by ronaldtse** [comment]
Let's close this and start a new one then. Thanks @frank-trampe !
