### ISSUE TITLE
Testing Ciphering and Encryption algorithms

### ISSUE THREAD

**Issue by MohitKumarAgniotri** [riboseinc/rnp#190]
Hi All,
I have been trying for last few days to develop test cases to generate keys using different ciphering and encryption algorithms but I am yet unable to figure out a way to verify the generated key to ascertain that the generated key is correct as per the requirement. 

**Any pointers would be appreciated.**

**Comment by dewyatt** [comment]
You'll probably have to use GPGME (see #189)

**Comment by MohitKumarAgniotri** [comment]
Thanks for the heads up. is there anyone working on #189? if not, I will start to make an initial attempt on using it.

**Comment by ronaldtse** [comment]
@dewyatt @flowher @zgyarmati  do you have experience with selectively including a library via autotools, in this case, GPGME only for compatibility tests?

**Comment by catap** [comment]
@ronaldtse I do a lot of experiences with autotools :) I think I can help.

**Comment by ronaldtse** [comment]
@MohitKumarAgniotri could you work with @catap on this? Thanks!

**Comment by MohitKumarAgniotri** [comment]
sure!  I will align with @catap.

**Comment by flowher** [comment]
We do it via, ``cli_tests.py`` currently. I think this ticket can be closed

**Comment by ronaldtse** [comment]
Indeed. Very happy to close this now.
