### ISSUE TITLE
Signing a file should respect keyring location options

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#2]
This works:
```
rnp --sign --homedir=/tmp/f0d9c5614f47f4f6/ $filename
```

This doesn't work:
```
rnp --sign --keyring=/tmp/f0d9c5614f47f4f6/secring.gpg $filename
```

This is the same for `rnpkeys` too.

**Comment by ronaldtse** [comment]
@ni4 @dewyatt Is this still valid? Thanks!

**Comment by ni4** [comment]
@ronaldtse Yes, rnp behaves the same way now. However it is logical - homedir should be dir, not file.
And we have #487 which will deal with key(s) from file, not homedir.
So this can be safely closed.

**Comment by ronaldtse** [comment]
Thanks @ni4 for the confirmation!
