### ISSUE TITLE
rnp generated keys should be compatible with GnuPG (can be used by GnuPG)

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#203]
From @frank-trampe #19:

> I was able to generate a key without a passphrase and to encrypt and to decrypt with that key. But gpg is unable to use the resulting key.

**Comment by ronaldtse** [comment]
@frank-trampe seems that #200 may not have this issue. Would you mind trying out that branch?

**Comment by ni4** [comment]
This is not the issue anymore, so closing it.
