### ISSUE TITLE
rnp and gpg homedir options are not compatible.

### ISSUE THREAD

**Issue by frank-trampe** [riboseinc/rnp#204]
The `--homedir` option means different things to gpg and rnp. gpg looks for key data in the specified directory. rnp looks in the `.rnp` subdirectory of that directory.

**Comment by frank-trampe** [comment]
This is similar but not identical to #1.

**Comment by dewyatt** [comment]
Correct, see https://github.com/riboseinc/rnp/pull/81 and https://github.com/riboseinc/rnp/issues/44#issuecomment-291787408

**Comment by ni4** [comment]
I am closing this issue since PR #258 fixes it by changing the way --homedir is handled on CLI. Now it is direct path to the folder with keyrings (however, without this option it is still ($HOME)/.rnp
