### ISSUE TITLE
Remove Elgamal sign operation

### ISSUE THREAD

**Issue by flowher** [riboseinc/rnp#205]
It seems RFC 4880 doesn't support Elgamal (PK algo ID 20) signature anymore (see 14.9 and ftp://ftp.inf.ethz.ch/pub/crypto/publications/Bleich96.pdf)

The goal of this ticket is to remove sign operation with elgamal scheme

**Comment by ni4** [comment]
Elgamal signing is obsolete, however signature verification may be left for compatibility with old messages?

**Comment by flowher** [comment]
This is just to make sure we don't create signatures

**Comment by flowher** [comment]
hmmm... actually looking again at the code - it's not possible to create elgamal signature or key for sigining.
