### ISSUE TITLE
rnpkeys --import-key should actually save to disk

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#21]
Currently it only imports to an in-memory keyring and does not save to disk.

**Comment by ronaldtse** [comment]
I suppose it should have been called `--import-key-and-discard` ;-)

Let's fix this soon.

**Comment by ni4** [comment]
Since this is related to CLI I will take this issue, just hit it with tests.

**Comment by dewyatt** [comment]
@ni4 I had to go ahead and do some work on this one to get CI passing after making some things stricter on error checking. Definitely room for improvement, but it does at least save to disk for the usual cases now.

**Comment by ni4** [comment]
@dewyatt Go ahead, I doubt that I'll get time for this soon.

**Comment by flowher** [comment]
@dewyatt It's done, isn't ? Can we close?

**Comment by dewyatt** [comment]
Yep, closing.
