### ISSUE TITLE
CI and local build scripts should use all processor cores

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#213]
Currently there's a few places where we have things like `make -j2`.
Many of us have 4 or more cores so when we build locally, this is a bit slower than what we expect.

I usually use something like `make -j$(grep -c '^$' /proc/cpuinfo)` which works well as long as procfs is mounted, etc.
I think we ought to default to 2 cores and then use /proc/cpuinfo to adjust if it's available.

**Comment by ronaldtse** [comment]
Agree with @dewyatt .
