### ISSUE TITLE
macOS compatibility broken on updates

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#214]
Running `build.sh` on macOS gives this error.

```
checking whether BOTAN_HAS_PGP_S2K is declared... no
configure: error: Botan build is missing a required feature
```

Obviously this is due to botan version (and that S2K isn't released yet), but there ought to be a way to make this work properly.

**Comment by ni4** [comment]
It doesn't work if 'brew install botan', however works fine if build botan from sources, using the master branch.

**Comment by ronaldtse** [comment]
Yes @ni4 , currently rnp requires botan from its latest master branch, but @randombit says he will have everything merged by botan 2.2, so we can probably rely on normal botan then.

**Comment by ronaldtse** [comment]
@ni4 we actually have a homebrew tap + formula here https://github.com/riboseinc/homebrew-rnp . Perhaps you could help maintain it so as to provide a one-liner install for rnp on macOS?

**Comment by ni4** [comment]
@ronaldtse Sure, I can be responsible for this.

**Comment by ni4** [comment]
@ronaldtse Maybe we can close this since homebrew formula works fine now?

**Comment by ronaldtse** [comment]
Yes indeed. Thanks!
