### ISSUE TITLE
pgp_add_time needs some refactoring

### ISSUE THREAD

**Issue by ni4** [riboseinc/rnp#219]
It's a bit weird - it has char* parameter type, which can be "birth" or "expiration", and then it is mapped to `tag = (strcmp(type, "birth") == 0) ? PGP_PTAG_SS_CREATION_TIME : PGP_PTAG_SS_EXPIRATION_TIME`

I think char* parameter should be replaced to some enum or directly to the `PGP_PTAG_SS_CREATION_TIME/PGP_PTAG_SS_EXPIRATION_TIME`

**Comment by dewyatt** [comment]
Agreed, it's a bit error-prone the way it is.
