### ISSUE TITLE
Remove sshkeydir

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#224]
I've been meaning to file an issue about this.
Currently we have a lot of calls like `rnp_setvar(&rnp, "sshkeydir", "/etc/ssh")`.
But this is not used by the library at all currently.

**Comment by ronaldtse** [comment]
Let's remove them then. I think we need a more comprehensive approach if (which we will) want SSH compatibility. @catap seems to have some ideas on doing it.

**Comment by ni4** [comment]
@dewyatt I'm currently removing those calls as part of the other issue so all will be fine :)

**Comment by ni4** [comment]
Done as side-effect of  PR #258. So closing this.
