### ISSUE TITLE
rnpkeys doesn't tell that entered passwords do not match during the generation

### ISSUE THREAD

**Issue by ni4** [riboseinc/rnp#227]
During the generation, If password and repeated password do not match, it just silently asks for the password again. However it should write some meaningful message, like 'Passwords do not match, please try again'.
It's just minor things however should be fixed at some point.

**Comment by ni4** [comment]
@dewyatt This seems to be fixed now, with introduction of passphrase_provider_t?

**Comment by dewyatt** [comment]
Good point, closing!
