### ISSUE TITLE
Generated secret keys always have 65536 as iteration count for s2k

### ISSUE THREAD

**Issue by ni4** [riboseinc/rnp#231]
GnuPG uses much higher iteration count: 13107200 or 7864320, depending on installation.
We should also pick up  better default encryption algorithm (currently CAST5 is used).

**Comment by randombit** [comment]
This could be an additional parameter to the keygen structure added in #241

**Comment by ni4** [comment]
Hm, s2k parameters are not part of key generation but part of secret key saving process - i.e. user logically is able to take already generated key, change security parameters (add/change/remove password, strengthen s2k) and save the key again.

**Comment by randombit** [comment]
Yeah true - I think the code would need to be refactored to split up these two operations.

**Comment by dewyatt** [comment]
Just adding this note for when someone works on this: The way gpg appears to handle this is it calculates an iteration count that takes ~100ms on the current machine, and uses that (see [here](https://github.com/gpg/gnupg/blob/5cf95157c5db88dd599ac4d48f619782179b1438/agent/protect.c#L163)).

IIRC another piece to keep in mind is that there is the RFC encoding of the iteration count, and then there's another encoding that gnupg sometimes uses (can't really recall).

**Comment by ni4** [comment]
Their approach seems to be a bit weird. Stuff which is encrypted on slow computer should not be less secure. I think better and simpler approach is to just declare default constant which is secure for nowadays and update it every year or so. And of course add configurable parameter for this.

**Comment by dewyatt** [comment]
> Their approach seems to be a bit weird. Stuff which is encrypted on slow computer should not be less secure.

I think the idea is probably to keep up with advances in hardware, without requiring occasional software updates just to change the iteration count? They do enforce a lower limit (65536) at least.

> I think better and simpler approach is to just declare default constant which is secure for nowadays and update it every year or so. And of course add configurable parameter for this.

I actually think the calibration approach may be better, if combined with a growing lower limit every year. Think about the case where you're using the newest high-end machine with all kinds of specific hardware acceleration. Such a machine may have the *potential* to use a much higher iteration count (without noticeable delays) than other machines, and so it may as well default to doing that.

So I think a machine-specific calibration combined with a growing lower limit might be a good compromise.

**Comment by ni4** [comment]
We also forgot another small thing - default iteration count should also depend on hash algorithm. It must be higher for weaker hashes and vice versa.

**Comment by ni4** [comment]
See the issue #531

**Comment by dewyatt** [comment]
I just wanted to note that I looked at the iteration count for a key generated with rnp today and one generated with gpg and have:

| tool | iterations |
| ------------- | ------------- |
| rnp  | 524288 |
| gpg | 33554432 |

So gpg generates keys that use an iteration count 64x what rnp uses on my machine. I'm thinking we should do something about this before any official release.

**Comment by randombit** [comment]
Fixed in #728
