### ISSUE TITLE
Implement file encryption with password

### ISSUE THREAD

**Issue by ni4** [riboseinc/rnp#238]
## Description

OpenPGP standard allows file encryption with password(s), without using the public keys.

**Comment by ronaldtse** [comment]
I know both botan and OpenSSL offer utility functions for standalone file encryption, but maybe we can make it simpler to use?

**Comment by ni4** [comment]
I'm not sure what encryption standard is used by botan/OpenSSL (CMS?). But at least OpenPGP password-encrypted document can be decrypted by GnuPG on any *nix system or by any PGP software or library (PGP Desktop, whatever else) on Windows.

**Comment by ronaldtse** [comment]
@ni4 could you take on this task? We could use this on a project by end of this month. Thanks!

**Comment by ni4** [comment]
@ronaldtse Ok, sure.

**Comment by ronaldtse** [comment]
@ni4 just to confirm that stream processing will mean (given a block size of b, available bytes of a, and a total length of n inside a packet):
* `0 < a < b`  => queued
* `b <= a < n`   => process block (encrypt / decrypt)
* fully available packet (`a == n`) => process packet (encrypt / decrypt)

Right?

**Comment by ni4** [comment]
@ronaldtse What do you mean under the block size?
Under the streamed processing I mean that data is read from the source, processed, and written out in one pass and using the constant-size cache (say, 32kb). It doesn't depend on packet sizes/partial data lengths and type of the input - the only requirement for the input is to be able to read data, and inform about the end of data. So, after initialization, in cycle we read some amount of data from input, then decrypt, then decompress, and then write to the output.

**Comment by ronaldtse** [comment]
Ah I got confused, thanks @ni4 .

**Comment by ni4** [comment]
Done in #463
