### ISSUE TITLE
GnuPG 2.1 keys will fail to parse (Issuer Fingerprint)

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#24]
This is due to the addition of an experimental signature subpacket (the issuer fingerprint SIGSUBPKT_ISSUER_FPR).

**Comment by ronaldtse** [comment]
@dewyatt just to clarify: both secret keys and public keys generated by GnuPG 2.1 fails to get imported?

**Comment by dewyatt** [comment]
@ronaldtse Correct. For example, I have GnuPG 2.1.19. All keys generated, public and secret, have this experimental signature subpacket that is currently unsupported in rnp and will cause pgp_parse to fail.

pgpdump will show what I suspect is the culprit as "Hashed Sub: unknown(sub 33)(21 bytes)".

The fix may be very simple, I just haven't looked into it yet.

**Comment by dewyatt** [comment]
(Side note: Another incompatibility with GnuPG 2.1 would be the new keyring format (.kbx), but maybe that doesn't matter right now.)
