### ISSUE TITLE
Check pgp_keyid function's hash parameter usage 

### ISSUE THREAD

**Issue by ni4** [riboseinc/rnp#252]
## Description

As it is observed in signature.c, signing methods send hash_alg to the pgp_keyid() function call. However that hash_alg should be used for data hashing not the fingerprint calculation.

This should be fixed after refactoring is finished.

**Comment by ronaldtse** [comment]
Agree. A v4 key fingerprint is always performed using SHA-1 according to RFC 4880:

> A V4 fingerprint is the 160-bit SHA-1 hash of the octet 0x99, followed by the two-octet packet length, followed by the entire Public-Key packet starting with the version field.  The Key ID is the low-order 64 bits of the fingerprint.

**Comment by ni4** [comment]
To not forget - keyring->hashtype parameter seems to be used only to save hash algorithm for the key fingerprint, which is not needed.

**Comment by ni4** [comment]
Fixed in #302
