### ISSUE TITLE
Support RFC 6637 (ECC for OpenPGP)

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#27]
[RFC 6637](https://tools.ietf.org/html/rfc6637) defines ECC usage in OpenPGP.

Specifically, it defines:

* ECC Curves: "Curve P-256", "Curve P-384", and "Curve P-521".
* Public Key Algorithms with ID 18 (ECDH public key algorithm) and 19 (ECDSA public key algorithm)

Support of Ed25519 (EdDSA) is in a separate issue #109

**Comment by flowher** [comment]
#217

**Comment by flowher** [comment]
Last part  - ECDH is coming soon

**Comment by flowher** [comment]
Waiting for https://github.com/randombit/botan/pull/1135 to be reviewed and merged
