### ISSUE TITLE
Cleanup in rnp public API 

### ISSUE THREAD

**Issue by henrydcase** [riboseinc/rnp#271]
## Description

We should be testing if it is possible to correctly link any application against rnp. Currently (``86298b1d38694fced64715937800df51c5de9450``) it is not a case because after ``make install`` the only header file that get's coppied to ``/usr/include`` is ``rnp.h``. This file includes other header files, so as a developer I effectively need some sources of rnp in order to build an app against it.

Other solution is to remove possibility to build application that links against ``rnp``.

Obviously this also requires refactoring of interfaces as types internal to rnp cannot be used in rnp.h. I propose using opaque data types and provide accessors.

Test app should preferably be C++ based as it will give us additional type checking.

This issue is indirectly/somehow related to #153.

**Comment by ronaldtse** [comment]
@flowher I agree. Let's come up with a good public API first and we refactor to that!

**Comment by flowher** [comment]
#441

**Comment by ni4** [comment]
@ronaldtse I think this can be closed now?

**Comment by ronaldtse** [comment]
Agree, thanks @ni4
