### ISSUE TITLE
Standardized signature extensions (.asc, .sig, .gpg)

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#272]
## Description

There are a number of places we differentiate `.asc`, `.gpg`, `.sig` manually. It should not be the case.

## Steps to Reproduce

1. `git grep "\.asc"` etc.

(see comment in #270)

## Expected Behavior

Only one line such as:
```c
#define RNP_ARMORED_SIG_ASCII_FILE_EXT ".asc"
```

## Actual Behavior

A long list of hardcoded file extensions is shown.

**Comment by ni4** [comment]
Btw, why do we stick to gpg extension for the default output? Actually we work on OpenPGP library, not GnuPG-compatible, so probably it is better to use .pgp extension? RFC doesn't seem to write anything regarding the default extensions.

**Comment by ronaldtse** [comment]
> A standardized-interoperable solution is always better than a proprietary one.

Let's discuss!

P.S. I agree with @ni4 .

**Comment by ronaldtse** [comment]
Related to #270 where "asc" and "gpg" are hardcoded.

**Comment by ni4** [comment]
Should be fixed in 1e5df364260f2b7795935e161110736b16d9eb85
