### ISSUE TITLE
Need of `libverify`

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#275]
## Description

`libverify` was previously used to support `rnpv` for a very light verification library, but since we're going to merge `rnp` and `rnpv` ( #69 ), `libverify` is no longer useful.

@ni4 suggests we should we remove it. What do you think?

Personally I believe just `librnp` is good enough, and signing/verification functionality should be placed together.

**Comment by flowher** [comment]
Maybe I'm missing a point, but I don't see why too keep it as separated binary.

**Comment by ronaldtse** [comment]
@flowher #69 describes several approaches for the command line util. Several individuals have mentioned that it is hard to use multiple CLIs, and for people who come from GnuPG expect everything provided in one binary.

We can always take an approach with aliasing, such as `alias rnpk=rnp --keys` or the other way round.

**Comment by ronaldtse** [comment]
What do you think @catap @dewyatt ?

**Comment by catap** [comment]
@ronaldtse I agree with you

**Comment by ronaldtse** [comment]
@ni4 would you like to handle the culling of `libverify`? 😉

**Comment by ni4** [comment]
@ronaldtse sure, will cut it out
