### ISSUE TITLE
Segfault when user-id contains special character

### ISSUE THREAD

**Issue by MohitKumarAgniotri** [riboseinc/rnp#276]
## Description

RNP library segfaults when trying to retrieve the key using user id which contains special characters like *

## Steps to Reproduce

1. Generate a key 
2. try to find/export the key 
    example: rnpkeys --find-key --userid=*
                   rnpkeys --export-key --userid=*max
3.  Observe segfault

## Expected Behavior

1. No segfault.
2. A Proper key is exported or listed.

## Actual Behavior

Segfault was observed when the commands were executed.

**Comment by dewyatt** [comment]
Great find @MohitKumarAgniotri!
We can see a bit more info with `rnpkeys --debug=key_store.c --find-key --userid=*`.

`regcomp` return value needs to be checked:
https://github.com/riboseinc/rnp/blob/e98911dc3b00eed847c4b5e28e387a8e5b7bb7ab/src/lib/key_store.c#L703

On a side note, the `--find-key` option doesn't actually list keys. It only affects the exit code of `rnpkeys`.

**Comment by catap** [comment]
@MohitKumarAgniotri can you confirm that it has gone?

**Comment by MohitKumarAgniotri** [comment]
@catap Sorry for being away! (got stuck in a sticky place). 
I will test it tonight and confirm. 
Apologies again for the delayed response.

**Comment by MohitKumarAgniotri** [comment]
Tested and couldn't reproduce the issue. LGTM.

**Comment by ronaldtse** [comment]
Thanks @MohitKumarAgniotri ! Closing now.

**Comment by ronaldtse** [comment]
Should we incorporate this in the CLI test suite?

@ni4 @dewyatt

**Comment by ni4** [comment]
@ronaldtse Sure, this should be added to CLI tests. I'll create an issue to not forget about it.
