### ISSUE TITLE
Move `ax_check_botan` into `/m4`

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#289]
## Description

`ax_check_botan` is at the root directory but the others are inside `m4/`. This should be done for consistency with #265.

## Steps to Reproduce

1. See root directory for `ax_check_botan.m4` file

## Expected Behavior

It is located at `m4/ax_check_botan.m4`

## Actual Behavior

At root now.

**Comment by dewyatt** [comment]
This and #290 have been on my mental TODO list. :)

**Comment by ronaldtse** [comment]
I knew that and glad it's now tracked 👍
