### ISSUE TITLE
Tests for CLI

### ISSUE THREAD

**Issue by flowher** [riboseinc/rnp#294]
We need test cases that test tools which are called from command line. It seems to me that some tests are already available in ``/tests`` directory - maybe this could be good starting point.

**Comment by flowher** [comment]
@MohitKumarAgniotri It's just FYI - I think it would fall somewhere under yours responsibility

**Comment by ronaldtse** [comment]
I think @ni4 was going to do something about it, he already had a python script.

**Comment by ni4** [comment]
@ronaldtse Yeah, I planned to add some tests for the CLI once finished with gluing together rnp + rnpkeys.  So we can assign this task to me.

**Comment by ronaldtse** [comment]
Thanks @ni4 !

**Comment by ni4** [comment]
@ronaldtse I think we can close this issue since we already have tests for CLI? They needs to be updated to cover some specific areas, but this issue could be considered as resolved.

@dewyatt Could you please integrate ./cli_tests.py with Travis? Should I create an issue for that?

**Comment by ronaldtse** [comment]
Thanks @ni4, and please do create an issue for @dewyatt on Travis integration !

**Comment by dewyatt** [comment]
> @dewyatt Could you please integrate ./cli_tests.py with Travis? Should I create an issue for that?

I think the challenge here will be that Travis CI is based on Ubuntu Trusty and we'll only have gpg 1.4 and 2.0 available. I think these tests are designed around 2.1, so we'll have to figure something out.
