### ISSUE TITLE
rnp_test_eddsa fails after numerous runs

### ISSUE THREAD

**Issue by ni4** [riboseinc/rnp#300]
## Description

After running 100-1000 iterations of rnp_test_eddsa it fails.
Most likely this depends on some parameters of randomly generated key - leading/final zeroes, high bits or so on.

## Steps to Reproduce

1. Checkout the branch ni4-eddsa-test-failure
2. make, make install, rnp_tests

## Expected Behavior

All 10000 iterations of rnp_test_eddsa run correctly.

## Actual Behavior

Test fails randomly after 100-1000 iterations.

**Comment by flowher** [comment]
@ni4 you can assign it to me if you want. I'll be happy to debug it

**Comment by ni4** [comment]
Thanks, @flowher !

**Comment by dewyatt** [comment]
If anyone is still looking into this, I just wanted to note that this is easily reproducible in current master with:
```
env RNP_TEST_ITERATIONS=1000 src/tests/rnp_tests
```
(much quicker if you comment out all tests except the eddsa one)
