### ISSUE TITLE
Extract out PGP packet parsing code to separate library

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#309]
## Description

PGP packet parsing is well-defined and the code can be self-contained.

This task is to extract out PGP parsing code to a separate library, e.g., `librepgp`.

Maybe these functions should be prefixed with `repgp_`?

**Comment by flowher** [comment]
Ok, ``repgp_`` it's gonna be

**Comment by ronaldtse** [comment]
Or:
1. `librepgp`
2. `libpgp`
3. `librgp` (`librpg` is already used)

Please vote: 😄  for 1, 🎉  for 2, ❤️  for 3.

**Comment by ronaldtse** [comment]
Without broader participation it looks like `librepgp` is the likely candidate 😉
