### ISSUE TITLE
Builds not working from outside the source tree

### ISSUE THREAD

**Issue by shaunwheelhouse** [riboseinc/rnp#31]
It would be helpful if builds were working outside the source tree but currently doing so fails due to an unresolved include:

```
../../../rnp/src/netpgpverify/main.c:37:10: fatal error: 'types.h' file not
      found
#include "types.h"
```

**Comment by zgyarmati** [comment]
I think it's on me, thanks for the report.
 I'll look into it after the name refactoring is done

**Comment by zgyarmati** [comment]
I think it's on me, thanks for the report.
I'll look into it after the name refactoring is done

**Comment by shaunwheelhouse** [comment]
No worries @zgyarmati! Thanks for the update and all the work on the re-naming effort, let me know if you could use a hand. 👍
