### ISSUE TITLE
FFI definition

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#324]
## Description

We need to define the FFI interface. We can base it on our usage from https://github.com/riboseinc/rnp (https://github.com/riboseinc/ruby-rnp/blob/master/example-usage.rb).

## Steps to Reproduce

N/A.

## Expected Behavior

N/A.

## Actual Behavior

N/A.

**Comment by ronaldtse** [comment]
@randombit would you be interested in helping us define the FFI? Your experience with defining the botan FFI would help us immensely with creating a stable yet flexible FFI.

**Comment by dewyatt** [comment]
I actually did some work on this yesterday, but it would certainly be nice to have Jack on this. He might be busy gearing up for the botan 2.2 release though.

**Comment by ronaldtse** [comment]
@dewyatt , @randombit for this until later but if you already have something done could you share it in some branch? I wonder if ruby-rnp could use what you have already?

**Comment by ni4** [comment]
@ronaldtse @dewyatt Can we close this since we have FFI interface already?

**Comment by ronaldtse** [comment]
Agree, thanks @ni4 !
