### ISSUE TITLE
Fix `make check` on macOS

### ISSUE THREAD

**Issue by catap** [riboseinc/rnp#330]
## Description

`make check` fails

## Steps to Reproduce

1. ./build_macos.sh
2. make check

## Expected Behavior
```
## --------------------------- ##
## rnp 0.8.0~ test suite: rnp. ##
## --------------------------- ##
  1: tests with no default userid in gpg.conf        ok
  2: init                                            ok
  3: attached signature and verification             ok
  4: encryption and decryption                       ok
  5: detached signature and verification             ok
  6: simple signature and verification               ok
  7: run rnp_tests                                   ok
```
## Actual Behavior
```
## --------------------------- ##
## rnp 0.8.0~ test suite: rnp. ##
## --------------------------- ##
  1: tests with no default userid in gpg.conf        ok
  2: init                                            ok
  3: attached signature and verification             ok
  4: encryption and decryption                       FAILED (crypt.at:13)
  5: detached signature and verification             ok
  6: simple signature and verification               ok
  7: run rnp_tests                                   ok
```

**Comment by catap** [comment]
Well, looks like something broke at master.

```sh
➜  rnp git:(master) ✗ ./build_macos.sh 
...
➜  rnp git:(master) ✗ rm -rf ~/.rnp                                     
➜  rnp git:(master) ✗ ./src/rnpkeys/rnpkeys --gen-key
rnp: default key set to "4E42FC58C5610C1DE8F30895642B66CD6A8959D9"
pgp_mem_readfile: can't open "/Users/catap/.rnp/pubring.gpg"
rnp_key_store_read_keyring: cannot read /Users/catap/.rnp/pubring.gpg
cannot read pub keyring
Generating a new key...
signature  2048/RSA (Encrypt or Sign) 67f86f1f49c00cac 2017-07-25 [] 
Key fingerprint: 23b1 ed69 5b02 1abe cc0d 2167 67f8 6f1f 49c0 0cac 
uid              4E42FC58C5610C1DE8F30895642B66CD6A8959D9
Enter passphrase for 67f86f1f49c00cac: 
Repeat passphrase for 67f86f1f49c00cac: 
➜  rnp git:(master) ✗ cp README.md test                                     
➜  rnp git:(master) ✗ cp test test.orig
➜  rnp git:(master) ✗ ./src/rnp/rnp --homedir ./tests/homedir --encrypt test
➜  rnp git:(master) ✗ wc test.gpg 
      11     102    3472 test.gpg
➜  rnp git:(master) ✗ ./src/rnp/rnp --homedir ./tests/homedir --decrypt test.gpg
➜  rnp git:(master) ✗ echo $?
1
➜  rnp git:(master) ✗ file test
test: cannot open `test' (No such file or directory)
➜  rnp git:(master) ✗ 
```

**Comment by catap** [comment]
@dewyatt, it is a current master:

```sh
#!/bin/sh -x

make clean 1>&2 2>/dev/null
./build_macos.sh 1>&2 2>/dev/null

rm -rf ~/.rnp
rm -f test test.gpg
cp README.md test

set -e
./src/rnpkeys/rnpkeys --gen-key
./src/rnp/rnp --encrypt test
./src/rnp/rnp --decrypt test.gpg

diff README.md test
```

output
```
.....
+ ./src/rnpkeys/rnpkeys --gen-key
rnp: default key set to "4E42FC58C5610C1DE8F30895642B66CD6A8959D9"
pgp_mem_readfile: can't open "/Users/catap/.rnp/pubring.gpg"
rnp_key_store_read_keyring: cannot read /Users/catap/.rnp/pubring.gpg
cannot read pub keyring
Generating a new key...
signature  2048/RSA (Encrypt or Sign) 9762df805a395e7e 2017-07-25 [] 
Key fingerprint: 64a1 1ab1 b17f a7b1 2a81 e001 9762 df80 5a39 5e7e 
uid              4E42FC58C5610C1DE8F30895642B66CD6A8959D9
Enter passphrase for 9762df805a395e7e: 
Repeat passphrase for 9762df805a395e7e: 
+ ./src/rnp/rnp --encrypt test
rnp: default key set to "4E42FC58C5610C1DE8F30895642B66CD6A8959D9"
./test.sh: line 12: 41579 Abort trap: 6           ./src/rnp/rnp --encrypt test
```

**Comment by catap** [comment]
Well...

I found first commit that's broke decrypt: ce4b5d60378769a3a8b98a46e2098467e7299068

If I use keypair that was generated and used to encrypt file before ce4b5d60378769a3a8b98a46e2098467e7299068, I can't decrypt the file since ce4b5d60378769a3a8b98a46e2098467e7299068

If I use a keypair and encrypted file that was created by ce4b5d60378769a3a8b98a46e2098467e7299068, it works at master.

If I use a keypair and encrypted file that was created by 68b3ef2d0d6ea97357a2dc4e7d5d64ef32f11f73 (before ce4b5d60378769a3a8b98a46e2098467e7299068), I can't decrypt the file by master.

**Comment by dewyatt** [comment]
I'll see if I can confirm later. We should test master/HEAD encryption with:

1. Generate new key with rnp

    * Encrypt with rnp, decrypt with rnp
    * Encrypt with rnp, decrypt with gpg
    * Encrypt with gpg, decrypt with rnp

2. Generate new key with gpg

    * Encrypt with rnp, decrypt with rnp
    * Encrypt with rnp, decrypt with gpg
    * Encrypt with gpg, decrypt with rnp

Or something along those lines.

**Comment by catap** [comment]
@dewyatt and we can easy implement this test at existed `make check` framework ;)

I will do it later today.

**Comment by ronaldtse** [comment]
@dewyatt I believe @ni4 will include the 1 and 2 tests in the CLI test suite.

**Comment by catap** [comment]
@ronaldtse anyway we have a proof that key pair that was generated before https://github.com/riboseinc/rnp/commit/ce4b5d60378769a3a8b98a46e2098467e7299068 can't be used at master and I think it is a very major bug.

**Comment by ronaldtse** [comment]
I agree @catap , I've created new issue #335 for this. Please help correct the issue description if it is not complete/correct. Thanks!

**Comment by ni4** [comment]
@ronaldtse @catap I stopped right in the middle of encryption/decryption CLI test, and was offline for a few days. Hopefully during the next days I'll find time to finish the suite.

**Comment by ni4** [comment]
It doesn't make sense anymore since we moved to cmake and moved to cmocka tests.
