### ISSUE TITLE
Copy tests data dir to tmp directory

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#338]
## Description

Not a priority, but just something I avoided doing before and made a mental TODO.

Basically the `src/tests/data` directory should be copied to the appropriate `/tmp/...` directory that is already created for each test, and then the `rnp_test_state_t->data_dir` should be set to that.
This would help prevent any state leak between the tests, etc.

The only reason I didn't do this before was because I didn't want to spend any time writing a copy_recursively function.

**Comment by ni4** [comment]
@dewyatt Since these are just tests, not a main functionality, what do you think about system('cp -r') ?

**Comment by dewyatt** [comment]
@ni4 I did have the same thought, since they're just tests. I think system ought to be fine (and if we end up with any quoting issues, maybe `execv` or something).

**Comment by catap** [comment]
@dewyatt as an option you can use `nftw`. But I agree with @ni4 that `system("cp -r")` is easy :)
