### ISSUE TITLE
Decryption of GPG encrypted file fails for 8-byte block size ciphers

### ISSUE THREAD

**Issue by ni4** [riboseinc/rnp#353]
## Description

Trying to encrypt the file with IDEA, 3DES, CAST5, BLOWFISH makes RNP fail with error message attached below. All of them have 8 byte block size, and all 16-byte ciphers work fine.
It could be something simple like disabled ciphers in botan, however it could be related to the block size.

## Steps to Reproduce

1. `gpg -e --cipher-algo CAST5 sample.txt`
2. `rnp --decrypt sample.txt.gpg`

## Expected Behavior
File is decrypted successfully

## Actual Behavior

```
packet-parse.c:2498: Unknown, Packet was not consumed
packet-parse.c:424: PGP_E_R_READ_FAILED, Read failed
packet-parse.c:3338: PGP_E_P_UNKNOWN_TAG, Unknown content tag 0xa
```

**Comment by ni4** [comment]
@dewyatt @randombit Maybe you have quick thoughts on this?

**Comment by dewyatt** [comment]
@ni4 Not able to reproduce on master, can you post the file? (`cat sample.txt.gpg | gpg --enarmor`)

**Comment by ronaldtse** [comment]
@ni4 we should have this tested in the CLI tests so we know for sure what exactly is failing and under what condition it fails?

**Comment by ni4** [comment]
@ronaldtse If it works on @dewyatt system then it is probably related to macOS  or my setup.
Command lines to quickly reproduce it (given that rnp and gpg are installed):
```
mkdir temp
cd temp
mkdir .rnp
mkdir .gpg
rnpkeys --homedir .rnp --generate-key --userid=cast5
echo "Hello, world" > hello.txt
gpg --homedir .gpg --import .rnp/pubring.gpg
gpg --homedir .gpg --cipher-algo CAST5 -e -r cast5 hello.txt
rnp --homedir .rnp --decrypt hello.txt.gpg
```

**Comment by ronaldtse** [comment]
@ni4 I know you're working on the PR for the CLI test suite, could you incorporate this test in there so it would be tested in Travis too? Thanks!

**Comment by ni4** [comment]
@ronaldtse Sure, it is already there. I'm testing all symmetric algorithms while encrypting with GPG side, and when it would be available as option - do the same from the RNP side.

**Comment by ni4** [comment]
This issue was fixed in some commit which did not reference it, so I'm closing it now.
