### ISSUE TITLE
CLI should allow selection of compression parameters

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#359]
## Description

From @ni4 #294:

> rnp supports decompression and by default compresses data, but we actually don't have a way to enable/disable compression or change the compression level yet

```sh
# off=0 ctb=c1 tag=1 hlen=3 plen=268 new-ctb
:pubkey enc packet: version 3, algo 1, keyid D78F04BE3AF65209
	data: [2048 bits]
# off=271 ctb=d2 tag=18 hlen=2 plen=71 new-ctb
:encrypted data packet:
	length: 71
	mdc_method: 2
# off=284 ctb=c8 tag=8 hlen=2 plen=36 new-ctb
:compressed packet: algo=2
# off=287 ctb=cb tag=11 hlen=2 plen=27 new-ctb
:literal data packet:
	mode b (62), created 1502000813, name="hello.txt",
	raw data: 12 bytes
```

rnp already implements ZIP, BZIP and ZLIB.

Relevant GPG options:
```
-z n
Set compression level to n. A value of 0 for n disables compression. Default is to use the default compression level of zlib (normally 6).

--compress-algo n
Use compress algorithm n. Default is 2 which is RFC1950 compression. You may use 1 to use the old zlib version (RFC1951) which is used by PGP. The default algorithm may give better results because the window size is not limited to 8K. If this is not used the OpenPGP behavior is used, i.e. the compression algorithm is selected from the preferences; note, that this can't be done if you do not encrypt the data.
```

**Comment by dewyatt** [comment]
> rnp already implements ZIP, BZIP and ZLIB.

Just a note, we do support all of these for decompression, but for compression we only support zlib.

Adding support for setting the zlib compression level shouldn't be difficult: https://github.com/riboseinc/rnp/blob/342fb12583ad98b45160460a3041790b8525ab25/src/lib/compress.c#L422

**Comment by ronaldtse** [comment]
@dewyatt Just created an issue on that 👍

**Comment by ni4** [comment]
I can take this and update CLI tests accordingly if nobody against it

**Comment by ronaldtse** [comment]
@ni4 please proceed, much appreciated!
