### ISSUE TITLE
Implement BZIP and ZIP OpenPGP compression

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#360]
## Description

From @dewyatt #359
> ... we do support all of these [ZLIB, BZIP and ZIP] for decompression, but for compression we only support zlib.

Adding support for setting the zlib compression level shouldn't be difficult: https://github.com/riboseinc/rnp/blob/342fb12583ad98b45160460a3041790b8525ab25/src/lib/compress.c#L422

This is also related to #359 which is CLI support for selecting these algorithms and setting compression parameters.

**Comment by randombit** [comment]
Should be fixed with #417, the CLI support is #359
