### ISSUE TITLE
pgp_ecdsa_sign_hash fails certain digest/curve combinations

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#364]
## Description

This test would actually be failing currently if we were checking the return value of `pgp_sig_write` in a certain place (PR coming), but it goes undetected because we fail to check that return value (though botan complains).

From what I can see, the logic here is causing botan to fail: https://github.com/riboseinc/rnp/blob/20cb9ad367cf414b9678b703b84a82fef38f634b/src/lib/ecdsa.c#L231
Botan wants to write the full 64 bytes, while this indicates a buffer size of 48 for this particular test.
Or something like that, I didn't look very closely.

## Steps to Reproduce

Look for the output `in botan_pk_op_sign_finish exception Invalid argument Encoding error: encode_1363: n is too large to encode properly` during test runs.

**Comment by flowher** [comment]
'r' and 's' is a value modulo multiplicative order of a base point. On the first sight code in rnp seems to be OK. 
Thanks for reporting it - I'll investigate that further.

**Comment by flowher** [comment]
Code in ``rnp`` seems to be correct - all tests work correctly when botan is compiled with rfc6979 module disabled (``./configure --disable-mod=rfc6979``). Short term it could be a solution, nevertheless I would prefer we don't disable this module in long term.

I need to do quick review of RFC6979 before proposing patch to botan.

**Comment by ronaldtse** [comment]
Thanks @flowher. @randombit any thoughts on this one?

**Comment by flowher** [comment]
I'm working on a fix

**Comment by flowher** [comment]
hmmm... It might also be that ``botan`` expects that message (digest) to be signed can't be longer than ``Signature_with_EMSA::max_input_bits()`` and then it means rnp needs to cut off few bytes from digest before signing.

**Comment by flowher** [comment]
Patch proposed https://github.com/randombit/botan/pull/1147. Not sure it's preferred way but seems OK according to spec, tests are OK and ... let's keep ball rolling.

**Comment by flowher** [comment]
Ok, finally after looking at botan documentation about PK_Signer - I think it's a bug in a ``rnp``. Rnp calls botan after digest of the message to sign has been produced - so we need to use "Raw" signing (we can't use EMSA). In this mode "if the message is too big, the signing operation will fail." So RNP needs to make sure that length of the digest is correct.
