### ISSUE TITLE
When generating ECDSA signaure deterministicly same hash algorithm must be used for HMAC_DRBG and signing

### ISSUE THREAD

**Issue by henrydcase** [riboseinc/rnp#367]
## Description

By default ``rnp`` uses RFC6979 for ECDSA signature generation. Currently we call ``botan_pk_op_sign_create(&signer, key, "Raw", 0)`` in order to create ECDSA signer. This call will always initialize HMAC_DRBG to SHA-512.

As per 3.3 of RFC 6979 we should initialize HMAC_DRBG with same hash algorithm as the one used for signing.

SHA2-512 seems to be safe default, but would be better to explicitly set an algorithm.

**Comment by flowher** [comment]
Alright. With this feature in botan we don't need anymore  #370. I'll take care of that

**Comment by randombit** [comment]
Fixed by #729
