### ISSUE TITLE
Add support for fully parsing and writing embedded signature subpackets

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#373]
## Description

Now that we have some basic subkey support, we will need to address this part of the RFC:

> A signature that binds a signing subkey MUST have an Embedded Signature subpacket in this binding signature that contains a 0x19 signature made by the signing subkey on the primary key and subkey.

and (worded differently):

> For subkeys that can issue signatures, the subkey binding signature MUST contain an Embedded Signature subpacket with a primary key binding signature (0x19) issued by the subkey on the top-level key.

Currently we don't fully parse embedded signature subpackets, and we don't support writing them. Priority is probably writing them.

**Comment by ronaldtse** [comment]
@ni4 would you have time to handle this issue? Thanks!

**Comment by ni4** [comment]
@ronaldtse Okay, sure.
