### ISSUE TITLE
rnp --list-packets SIGSEGV

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#375]
## Description

It looks like `rnp --list-packets` crashes on certain input.

## Steps to Reproduce

1. `echo test | src/rnp/rnp --clearsign --output data.asc`
2. `src/rnp/rnp --list-packets --armor data.asc`

## Expected Behavior

No segfault.

## Actual Behavior

Segfault.

**Comment by erikbor** [comment]
A 2 byte .gpg file can cause the crash:

```sh
$ uname -a
Darwin OF-OSX-007 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
$ echo -e "\xa0\x01" > foobar.gpg
$ rnp --list-packets --homedir=. foobar.gpg
=> PGP_PARSER_PTAG: Compressed Data

==== ptag new_format=0 type=8 length_type=0 length=0x1 (1) position=0x0 (0)
Compressed Data packet
=> Compressed Data
COMPRESSED packet
Compressed Data Type: 10
Segmentation fault: 11
```

**Comment by ni4** [comment]
Not an issue anymore since packet dumping code was rewritten.
