### ISSUE TITLE
rnp cleartext signature verification fails in some cases

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#376]
## Description

It looks like cleartext signature validation fails in some cases when newlines are involved.

## Steps to Reproduce

1. `echo test | src/rnp/rnp --clearsign --output data.asc`
2. `src/rnp/rnp --verify data.asc`

(Using `echo -n test` above would result in something that rnp *does* validate.)

gpg shows them as valid.

More interesting output can be obtained with something like `src/rnp/rnp --verify --debug=reader.c data.asc`.

**Comment by ni4** [comment]
@dewyatt I also experienced problems with cleartext/armored signature verification.
Looks like dearmoring code is broken or didn't work well at all.
@ronaldtse Is this of high priority now? Then I can take a look.

**Comment by ronaldtse** [comment]
Yes, this is important because users expect it to work and it is a common occurrence. Thanks @ni4 !

**Comment by ni4** [comment]
Fixed with #423
