### ISSUE TITLE
Parsing compressed data packet fails

### ISSUE THREAD

**Issue by flowher** [riboseinc/rnp#378]
## Description

Found during development of #309.

It seems that ``rnp`` fails to parse data after PGP_PTAG_CT_COMPRESSED. Test committed in branch ``GH_378`` at ``53da99bb9f7f05d7e2387dd49252abb7d55b9910`` reads correctly formatted packet from file, compresses it and writes to memory. Then tries to parse.

## Steps to Reproduce

1. Compile ``rnp`` from brnach GH_378
2. Run tests (all other tests are commented out)

## Expected Behavior

Packet is correctly parsed as in the ``pgp_parse_keyrings_1_pubring`` test 

## Actual Behavior

Following error is reported:
```
packet-parse.c:2498: Unknown, Packet was not consumed
packet-parse.c:424: PGP_E_R_READ_FAILED, Read failed
packet-parse.c:1300: PGP_E_PROTO_BAD_PUBLIC_KEY_VRSN, Bad public key version (0xa6)
packet-parse.c:3338: PGP_E_P_UNKNOWN_TAG, Unknown content tag 0x3c
```

**Comment by ni4** [comment]
Looks like I found the same issue yesterday, during the updating of CLI tests. rnp fails to verify a file signed by GPG, but things work fine if it is not compressed.

I can take this issue if nobody else wants to.

**Comment by ronaldtse** [comment]
@ni4 feel free to take it. Hope this will be addressed in the CLI tests!

**Comment by flowher** [comment]
Thnx!
