### ISSUE TITLE
Reboot passphrase handling (was: Passphrase communication is inconsistent)

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#39]
The mechanisms for providing passphrases seem a bit inconsistent.

The netpgp_* layers have a "pass-fd" variable that can be used to communicate a file descriptor where a passphrase can be written by client software when needed.

The lower-level pgp_* layers typically have a passfp parameter that is a file pointer where a passphrase can be written.

Additionally there are some outliers like:

```c
pgp_memory_t *
pgp_decrypt_buf(pgp_io_t *io,
                        const void *input,
                        const size_t insize,
                        pgp_keyring_t *secring,
                        pgp_keyring_t *pubring,
                        const unsigned use_armour,
                        const unsigned sshkeys,
                        void *passfp,
                        int numtries,
                        pgp_cbfunc_t *getpassfunc)
```

I'm not sure why this function has both a passfp and a getpassfunc callback parameter. On the ruby side I've not had any issues with sending a nil getpassfunc parameter and just using passfp.

Personally I think a callback mechanism might make the most sense for providing a passphrase, like gpgme does. A callback also clearly communicates that a passphrase is required, unlike the unidirectional pipe pass-fd/passfp.

(Side note: pgp_parse does use a callback PGP_GET_PASSPHRASE, but everything else generally does not)

**Comment by ronaldtse** [comment]
It would be the easiest if we consolidate all of these functions (that could take passphrases) to only support only one passphrase passing method.

For example, we can implement `pass-fd` or `passfp` using the callback method anyway.

What do the others think? Pinging expert @randombit , @shaunwheelhouse @zgyarmati .

(`pgp_decypt_buf` itself seems to take way too many unnecessary arguments too.)

**Comment by ronaldtse** [comment]
In addition, in places that passphrases are checked, the error code should be consistently returned to the user indicating passphrase mismatch.

**Comment by zgyarmati** [comment]
Ah, i made a typo in my commit msg, so reopening this, sorry for the noise!

**Comment by ronaldtse** [comment]
@riboseinc/rnp Let's use this to settle on a "correct" passphrase handling structure that is solid and secure.

**Comment by dewyatt** [comment]
Done!
