### ISSUE TITLE
Integrate CLI tests to Travis

### ISSUE THREAD

**Issue by ni4** [riboseinc/rnp#394]
## Description

`cli_tests.py all` should be run in Travis to ensure that CLI works correctly among with cmocka tests.

However, comment from @dewyatt :

> I think the challenge here will be that Travis CI is based on Ubuntu Trusty and we'll only have gpg 1.4 and 2.0 available. I think these tests are designed around 2.1, so we'll have to figure something out.

So probably we should adjust tests to check GnuPG version and run correctly together with 1.4.x, 2.0.x, 2.1.x.

**Comment by ronaldtse** [comment]
@ni4 GnuPG 2.1 is available with Travis' macOS and also our own macOS via homebrew. We can start with that first?

Also GnuPG 2.1 seems possible to be installed on Ubuntu except it would take some time:
https://gist.github.com/mattrude/3883a3801613b048d45b

**Comment by dewyatt** [comment]
Installing it to some build directory is a good idea, and we can add that directory to the travis cache so it doesn't slow things down.

**Comment by ronaldtse** [comment]
Would someone be ready to take this on? We badly need CLI tests in CI.

**Comment by dewyatt** [comment]
I'm going to just get this done right quick.
