### ISSUE TITLE
Proposal: Key unlocking

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#396]
## Description

The proposal here is to add the concept of locking/unlocking an encrypted secret `pgp_key_t`.
This would be somewhat synonymous with the concept of an encrypted/unencrypted/protected/unprotected key, but this would be for in-memory keys and not a storage attribute.

This would basically be a toggle for encrypted secret keys that would switch between having unpopulated/populated MPIs in `key->key.seckey`.

## Use Cases

As a quick example, let's say you had an application that has some keys in memory and it occasionally needs to create a batch of signatures (maybe a few thousand). It could unlock the key, provide the passphrase once, sign all those things, and then re-lock it and keep it in memory until the next batch of signatures is required.

## Implementation

I think the simplest initial approach may work something like:

* `unlock_key (pgp_key_t *)`
  * Request the passphrase, decrypt the MPIs and fill them in within the pgp_key_t (so the MPIs are now filled in and available for sign/decrypt/etc without a passphrase).
* `lock_key (pgp_key_t *)`
  * Free/zero the MPIs. The encrypted key packet remains available in `pgp_key_t->packets[0]` for later unlocking.

For keys that were loaded without any encryption (for example, `s2k_usage = 0`), these would be a no-op (at least I think that would be easiest for an initial implementation).

I know we're on (/past) a deadline but I've been working on passphrase handling and I think this could be easily added as I finish this up.

**Comment by ronaldtse** [comment]
I fully agree with @dewyatt on this approach. Would be fantastic to use this 👍

**Comment by ni4** [comment]
I also fully agree on this. So, for instance, sign/decrypt methods would first check whether key is unlocked and only then ask for passphrase and so on.

**Comment by dewyatt** [comment]
Done!
