### ISSUE TITLE
Unifying and documenting versioning

### ISSUE THREAD

**Issue by zgyarmati** [riboseinc/rnp#40]
Currently we have the autoconf package version in configure.ac and a hand-maintained version value in version.h, these need to be unified and the scheme documented.

**Comment by ronaldtse** [comment]
@zgyarmati how about we re-start the versioning from 0.8.0 since there are a number of issues to be taken care of right now? Thanks.

Rationale:
* not yet production-ready for 1.0
* but far ahead of a 0.1

**Comment by ronaldtse** [comment]
Thank you @zgyarmati !

**Comment by ronaldtse** [comment]
@zgyarmati , the changes right now aren't compatible with the existing RPM building process. Could you please help fix this? Thanks!

1. 
Due to these calls to `git`, the RPM building fails as the RPM is built in a separate directory from an immediately packaged archive (which is not a git repo):

``` bash
configure.ac:AC_REVISION([m4_esyscmd_s([git describe --always])])
configure.ac:AC_DEFINE([GIT_REVISION],["m4_esyscmd_s([git describe --always])"],
configure.ac:AC_MSG_NOTICE([Git revision:        m4_esyscmd_s([git describe --always])])
```

Causing these messages during the `autoreconf -ivf` line in the `rnp.spec`:
``` bash
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
...
```

2.
Due to the generation method of `PACKAGE_VERSION`, we need to first run `autoconf` prior to running the build script for packaging the RPM:

``` bash
cd /usr/local/rnp
packaging/redhat/extra/prepare_build.sh
autoreconf -ivf   ## This line is necessary
packaging/redhat/extra/build_rpm.sh
```

Instead of just:
``` bash
cd /usr/local/rnp
packaging/redhat/extra/prepare_build.sh
packaging/redhat/extra/build_rpm.sh
```

**Comment by zgyarmati** [comment]
Thanks for looking into this! Indeed, I've put aside to keep the .rpm packaging in sync a bit, as first i want to manage the libmj->libjson-c migration first as it will bring in a new dependency. Also, the way the botan and cmocka dependency as handled at the moment is sub-optimal, which we also have to discuss.
 Generally speaking: first i would like to manage the new dependencies in the codebase itself, and when they are finalized get back to bringing up the rpm (and later .deb) packaging to that level. Is that sounds OK to you or i should swap the priorities?

**Comment by ronaldtse** [comment]
* CMocka: we now use a yum package for its functionality, which works.
* Botan there is an existing yum package but only for 1.0, @ribose-jeffreylau has contacted the package maintainer to request a newer 2.x package, so when that's done we can use a yum package.

For libjson-c there is a 0.11 RPM (json-c.x86_64 0:0.11-4.el7_0) but not the latest 0.12. 

@ribose-jeffreylau could you also contact the package maintainer to update to [json-c 0.12](https://github.com/json-c/json-c/releases)?

The current priorities are good, thanks!

**Comment by ronaldtse** [comment]
@ni4 @dewyatt can we close this? Thanks!

**Comment by ni4** [comment]
@ronaldtse I think so.

**Comment by ronaldtse** [comment]
Thanks for the confirmation!
