### ISSUE TITLE
CFB resync is broken

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#403]
## Description

See https://github.com/riboseinc/rnp/pull/401 for more discussion.

AFAICT this isn't something that broke recently and may have always been broken in netpgp.

## Steps to Reproduce

One impact of this is that encrypted V3 keys are not usable. To demonstrate, use the keys below (password 'test').

1. `gpg --dearmor < secring.gpg.asc > ~/.rnp/secring.gpg && gpg --dearmor < pubring.gpg.asc > ~/.rnp/pubring.gpg`
2. `echo hi | src/rnp/rnp --sign` (won't work)
3. `echo hi | gpg --homedir=~/.rnp --sign` (will work)

`secring.gpg.asc`
```
-----BEGIN PGP ARMORED FILE-----
Comment: Use "gpg --dearmor" for unpacking

lQGxAzvqRosAAAEDeNMKLJMJQeGC2RG5Nec6R2mzC12N1wGLiYYJCsmSQd1Y8mht
A2Sc+4k/q5+l6GHtfqUR/RTCIIudAZUzrQVIMhHDKF+5de9lsE5QxQS1u43QGVCb
/9IYrOLOizYQ2pkBtD9LCrf7W2DccMEkpQKD8QAFE/8DAwKCmfCK/R7eN9JRAyab
Z9omBAN3pmFiDt0EYNc8dLkVxDKTGr8RNzhN35VUyj4VYrPPbOTsMBbLCLOpdCBF
pphXdGEQI/iDtzznfvXnDvMWxqFCZtAZJkH0J8Z+vEN33Rx0zflmuOs8DMuGRxUn
lk2YQKmveafKnl2k5AxoHt6i4FucAbzofwcVmX7Gb9UW9PK4NSN19WIsnCG2/CL7
kTvoCdMze9fNrpAcfNhJxEgi0H7RO0f1bb5Sh9G8IAG8BogNO/oGBwyc+5C60h80
svQd1xnO5ehnOzcs2ZlskiKorVE3389m3HO59bupxZMVxdL25K/j1ysBsd/9LGgp
loM+OgKGfkaWZkm1HALO7nYoqotutb4xJkDLNw9lYCxRm9oAUQKZ4WtY5W+5BeaV
fzSC6LQRcGdwMi42LjMtdGVzdC1rZXk=
=WcmK
-----END PGP ARMORED FILE-----
```

`pubring.gpg.asc`
```
-----BEGIN PGP ARMORED FILE-----
Comment: Use "gpg --dearmor" for unpacking

mQB8AzvqRosAAAEDeNMKLJMJQeGC2RG5Nec6R2mzC12N1wGLiYYJCsmSQd1Y8mht
A2Sc+4k/q5+l6GHtfqUR/RTCIIudAZUzrQVIMhHDKF+5de9lsE5QxQS1u43QGVCb
/9IYrOLOizYQ2pkBtD9LCrf7W2DccMEkpQKD8QAFE7QRcGdwMi42LjMtdGVzdC1r
ZXmJAIQDBRA76kaL3HDBJKUCg/EBAZMoA3Yqqdix6B2RAzywi9bKSLqwAFVL+MMw
W+BnYeBXF9u+bPpQvtyxgi0vx8F9r84B3HAhZNEjBWODF6vctIQhXhAhXIniDTSj
HNzQ/+nbWnebQn18XUV2SdM1PzMOblD+nISte7+WUfWzlD7YUJPkFPywAgAD
=7PD0
-----END PGP ARMORED FILE-----
```

**Comment by dewyatt** [comment]
I meant to add that GPG v2.1+ doesn't support V3 keys anymore, and maybe we shouldn't either (they have issues).
https://www.gnupg.org/faq/whats-new-in-2.1.html

So ignoring the issue of V3 keys, my only question/concern about CFB resync being broken, is what are tag 9 packets used for? I know gpg < 2.1 uses them for password-only symmetric encryption, but I'm not sure what else. I think everything recent tends to use tag 18 since it has integrity protection.

**Comment by ronaldtse** [comment]
I agree that we should drop support for V3 keys for now. Tag 9 is probably only used for backwards compatibility today (which is a significant portion since GnuPG 2.1 is not yet offered in most of the stable Linux distros). Tag 18 is already described in the RFC bis as the preferred method. 

The thing about the OpenPGP standard is it doesn't provide clear versioning so it is hard to determine what exactly needs to be supported. The only indication of what should be supported seems to be purely defined by the implementation itself of GnuPG.
