### ISSUE TITLE
Licensing and copyright texts

### ISSUE THREAD

**Issue by zgyarmati** [riboseinc/rnp#41]
I would like to also unify the license and copyright texts in the source tree. Could you please specify the copyright holder and the license(s) to use?

**Comment by ronaldtse** [comment]
Copyright should be assigned to "Ribose Inc." and let's use the Simplified BSD license following our origin. I've pushed up `LICENSE.md` to reflect this change.

We should insert our copyright/license notice to the top of the source files without replacing previous notices by other copyright holders. Thanks!

**Comment by ronaldtse** [comment]
@zgyarmati this issue seems now complete, can we close it?

**Comment by zgyarmati** [comment]
Yep, thx
