### ISSUE TITLE
Create CLI test case for CFB resync/loading of v3 keys

### ISSUE THREAD

**Issue by ni4** [riboseinc/rnp#419]
## Description

It's not a good tone to write description like this but see  the #414 and #403, #401  for the info.

**Comment by ronaldtse** [comment]
A perfect description 😉

**Comment by ni4** [comment]
For a while we have cmocka tests (like `test_stream_key_decrypt`, `test_stream_key_encrypt`) for new key encryption/decryption, so those test cfb resync as well.
So I think this issue may be closed safely.
