### ISSUE TITLE
Implement streamed data processing

### ISSUE THREAD

**Issue by ni4** [riboseinc/rnp#424]
## Description

Within current implementation data is processed as a whole and processing results are stored in memory for later processing. So memory usage is a multiply of input size, which is wrong - it must be (and could be) constant except some rare circumstances (when we don't have one-pass signature? don't remember for sure right now).

So we need to switch to streamed processing, so input data will be handle like the following:
- input file is read to memory by chunks (say, 64k blocks)
- it is parsed and according to contents or operation data processors are created
- and this chunk of data passes through all processors up to the output file/memory/stdout

Say, for instance, for file encryption it could be like this:
- file_processor - processor which starts the chain and reads file by chunks in cycle
- data_hash_calculator for MDC
- data_compressor
- data_encryptor
- file_writer

For PGP data processing it would be a bit different since we don't know the packet contents from the beginning, so should insert some 'decision makers' which parse data and create processors on the go.

It could be divided into the following parts:

- [x] Implement streamed processing for symmetric encryption and decryption
- [x] Implement armouring/dearmouring streams
- [x] Move existing PK encryption and decryption to streamed processing
- [x] Implement streamed signing and verification of attached signatures
- [x] Implement streamed signing/verification for detached signatures
- [x] Implement streamed cleartext signing/verification

**Comment by ni4** [comment]
If nobody else wants to start with it I could begin while doing symmetric encryption/decryption support.

**Comment by ronaldtse** [comment]
@ni4 would be great if you could start with it! For OpenPGP packet processing if we reduce the packet size the same streaming approach would also work?

**Comment by ni4** [comment]
@ronaldtse Sure, it will not depend on packet size at all, it's just another approach/architecture.

**Comment by ronaldtse** [comment]
Sure, please proceed 👍

**Comment by catap** [comment]
@ni4 hey, have you got any ETA? :)

**Comment by ni4** [comment]
@catap I plan to finish streamed approach for symmetric encryption/decryption till the end of this week. Then, after discussion of PR, will get to PK encryption/signing/verification

**Comment by ronaldtse** [comment]
@ni4 any updates on this issue? Thanks!

**Comment by ni4** [comment]
@ronaldtse Now I'm finishing signature verification part. Hope to finish signing/verification during this week or beginning of the next one.

**Comment by ronaldtse** [comment]
Sounds good @ni4 , in this case @dewyatt could you use the new streaming sign/verify interface for the FFI?

**Comment by ronaldtse** [comment]
@ni4 just checking in -- are we close to completing the sign/verify? Thanks! 😉

**Comment by ni4** [comment]
@ronaldtse I got away for few days, will do more at the end of the week. Now streamed verification lacks only cleartext signatures, implementing which should not take a lot of time. Then I'll do PR for verification, and start work on signing.

**Comment by ni4** [comment]
Finally fixed, last commit is 1e5df364260f2b7795935e161110736b16d9eb85
