### ISSUE TITLE
rnp_init homedir check

### ISSUE THREAD

**Issue by shaunwheelhouse** [riboseinc/rnp#43]
It's not very idiomatic that netpgp_init/rnp_init performs an emptiness test on the homedir setting and raises an error if it isn't set. I propose that we change the interface from:

```
if (rnp_set_homedir(&context, new_home, key_directory, quiet))
    rnp_init(&context);
```

to either assuming a sane default (getenv("HOME"), ".gnupg") or accepting the homedir directory in the initialiser:

```
rnp_init(&context, getenv("HOME"), ".gnupg");
```

What are your thoughts?

**Comment by shaunwheelhouse** [comment]
It also seems that by zeroing the context structure during initialisation any previously set home directory variable is lost... causing apps to invariably fail. In the interest of getting it working for testing tonight I'm going to go with a sane default for the time being and shuffle set_homedir calls below the init call.

**Comment by ronaldtse** [comment]
@shaunwheelhouse agree. This direction is much more proper that what is there. Let's do this.

**Comment by shaunwheelhouse** [comment]
@ronaldtse There's currently a bug breaking key loading that has me holding off for a pull tonight but you can review today's work at my fork under the 'rnpkeys-init-fix' branch.

I haven't forgotten about the improved command line interface you'd like to see either. I'll move on to that once this and perhaps the asprintf dependencies are knocked out. 👍

**Comment by ronaldtse** [comment]
Thank you @shaunwheelhouse , this is giving us lots of hope 👍
