### ISSUE TITLE
Internal subdirectory handling

### ISSUE THREAD

**Issue by shaunwheelhouse** [riboseinc/rnp#44]
The following piece of boilerplate is/was present in all of the utilities:

```
rnp_set_homedir(&rnp, getenv("HOME"),
    rnp_getvar(&rnp, "ssh keys") ? SUBDIRECTORY_SSH : SUBDIRECTORY_GNUPG, 1);
```

I get the strong impression that switching for gnupg and ssh keys was a featured added much later and patched onto the existing `homedir` context registry setting. I suggest that we solve this by implementing the following behaviour:

* Three new registry settings: `homesubdir`, `homesubdir_gnupg`, `homesubdir_ssh`.
* Move the key type check to a getter for `homedir`.

When the home directory is read:

* Check whether or not the subdirectory for the current key type is not null (`homesubdir_gnupg` or `homesubdir_ssh`). If non-null then use that.
* Check whether `homesubdir` is non-null. If non-null then use that.
* Otherwise fall back to `SUBDIRECTORY_GNUPG` or `SUBDIRECTORY_SSH`.

Finally:

* Alter `rnp_set_homedir` to separately set the `homedir` and `homesubdir` settings. We can now pass `NULL` to the subdirectory parameter and get correct behaviour.

* Add an `rnp_get_homedir` function that performs the behaviour set out above.

**Comment by ronaldtse** [comment]
@shaunwheelhouse we will still allow setting `keydir`, `sshdir` separately from (to override) `homedir`/`$HOME`, right?

**Comment by shaunwheelhouse** [comment]
@ronaldtse for the subdirectories, yes. If we need keydir and sshdir to be able to be set to totally different paths, e.g.:

```
keydir: /home/myuser
sshdir: /home/myotheruser
```

a different design to what I suggest here would be necessary.

**Comment by ronaldtse** [comment]
@shaunwheelhouse suppose I could set the following either via arguments or environment variables:
```
homedir:/home/myuser/
keydir: /home/myotheruser/.rnp
```

Then the subdirectories will be set to:
```
sshdir: /home/myuser/.ssh
keydir: /home/myotheruser/.rnp
```

Correct?

**Comment by shaunwheelhouse** [comment]
@ronaldtse I hadn't yet seen the `sshkeydir` variable. The whole subsystem there is very spread out and inconsistent. I'll get back to you on this one.

**Comment by ronaldtse** [comment]
No problem @shaunwheelhouse . The key point is whatever we do must be consistent and clearly communicated with the user via `--help` and the man pages.

**Comment by shaunwheelhouse** [comment]
@ronaldtse I strongly agree. Unfortunately some of the frontend and some of the business logic connecting them to the library is inconsistent, but we'll repair that very soon.

**Comment by ronaldtse** [comment]
Hi @shaunwheelhouse just wanted to know if this is still being handled. Thanks!

**Comment by ni4** [comment]
I am closing this issue since PR #258 fixes it by getting rid of homedir option on library level. Now library works with public and private keyring paths, which are available in rnp_ctx_t structure.
