### ISSUE TITLE
Create a pgp-packet-dumper based on librepgp

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#442]
## Description

Originally discussed in #441.

[pgpdump](http://www.mew.org/~kazu/proj/pgpdump/en/) is an OpenPGP packet dumper.

GnuPG has a packet dumper too, output can be seen here:
https://davesteele.github.io/gpg/2014/09/20/anatomy-of-a-gpg-key/

## Expected Behavior

We should have a OpenPGP packet dumper that does exactly those things, just using the newly extracted `librepgp`.

Potentially more, e.g., listing packets out in different formats such as JSON).

This will also be a great demonstration of the completeness of `librepgp`.

**Comment by ronaldtse** [comment]
From @ni4 here
https://github.com/riboseinc/rnp/pull/441#issuecomment-327392173

> But pgp dumper will need to handle encrypted packet/compressed, which will require all the cryptography, compression and so on? This goes a bit beyond of the purpose of repgp as far as I understand it.

**Comment by ronaldtse** [comment]
@ni4 But all it needs is to read the packets (not decrypt), and show the {crypto,hash,compress} algorithm numbers etc.? `librepgp` should be able to do that right?

**Comment by ni4** [comment]
@ronaldtse Right, unless you hit the encrypted data packet. Without decryption you would be able just to tell information about the first public key/symmetric key encryption session key packets.
