### ISSUE TITLE
librekey: G10 ECC support

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#453]
## Description

I know @catap is already aware of this but I couldn't find an open issue referencing it, so here it is.
Currently the G10 format only supports RSA, DSA, ELG. Adding SM2 and others would be a good idea, but I do see it could take a bit of extra work.

(Side note: We may also want to add the other RSA identifiers in `parse_seckey`+`parse_pubkey`, seems to only have `PGP_PKA_RSA` right now).

**Comment by ronaldtse** [comment]
@ni4 would you have time to look into this issue? Thanks!

**Comment by ni4** [comment]
@ronaldtse Ok, I'll take a look!

**Comment by ronaldtse** [comment]
Looks like this one just came up here: https://github.com/riboseinc/enmail/issues/53

@ni4 perhaps you could have time to check? Thanks!

**Comment by ni4** [comment]
@ronaldtse  Okay, I finally have some time for this!
