### ISSUE TITLE
defkey for G10 depends on readdir order

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#458]
## Description

I think I forgot to create an issue for this:

> The defkey setting for G10 is likely incorrect, it relies on the order of readdir. So signing with a GPG21 keystore format typically requires --userid to hint at which key you actually want.

https://github.com/riboseinc/rnp/blob/e084a1c425cefb8628f759b1f8fe60e22949ed10/src/librekey/rnp_key_store.c#L180

In general, defkey probably needs to be more carefully chosen based on key flags and such.

## Steps to Reproduce

1. `rm -rf ~/.rnp`
2. `src/rnpkeys/rnpkeys --gen-key --keystore-format=GPG21`
3. `echo test | src/rnp/rnp --sign > data.gpg`
4. (Go to step 1 until you get an error that "this key can not sign")

**Comment by ni4** [comment]
@dewyatt My idea in default key picking would be to go through corresponding public keyring and pick first primary key, which has secret part in secret keyring. If there are no secret keys - then just first primary public key. Does this sound good?

**Comment by dewyatt** [comment]
@ni4 That sounds logical to me. I think that when I filed this I was concerned about the case of an empty pubring, but now that we support extracting the pub from sec, that case shouldn't be a problem.

Ideally we would look at the operation being requested and pick the default key based on that though. We can file that as a future enhancement if needed.
