### ISSUE TITLE
Decoding legacy PGP messages

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#480]
## Description

I received this email from a user, and don't know whether this still affects RNP today.

> I have a decode error with netpgp lib and when I try to decode a legacy pgp msg I get the following error: netgpg - " incorrect or unknown tag". With gpg v2 I see this error: gpg: WARNING: message was not integrity protected. With gpg v2 it decodes but with the WARNING. Any clue from you side what it could be?

## Steps to Reproduce

1. Attempt to decode a legacy OpenPGP message. I assume this is tag 9?

## Expected Behavior

GnuPG: `WARNING: message was not integrity protected` but decrypts.

## Actual Behavior

Apparently it fails with message `netgpg - " incorrect or unknown tag"`.

**Comment by ronaldtse** [comment]
@dewyatt @ni4 could you have a look at this? Thanks!

**Comment by ni4** [comment]
@ronaldtse Do you have such sample message or the way to generate it? Or at least output of `gpg --list-packets`? It is encrypted, and probably it is symmetrically-encrypted, then it should be support with rnp now.

**Comment by ronaldtse** [comment]
@ni4 I don't have the sample since it was a reported issue, I assume it was a Tag 9 Symmetric Encrypted packet since the gpg message says "not integrity protected".

If it's supported could you please close this then?

**Comment by ni4** [comment]
Ok, sure!
