### ISSUE TITLE
ECDH key should be created as subkey to ECDSA key

### ISSUE THREAD

**Issue by flowher** [riboseinc/rnp#488]
## Description

As mentioned in #344 the ECDH key generated by rnp can't be imported to GnuPG and other way around. At the time ECDH was implemented the functionality needed for generation a key with a subkey wasn't fully supported. 
Needed functionality for subkey generation is now implemented so we can carry on with ECDH key generation, so that it's  compatible with GnuPG

**Comment by ronaldtse** [comment]
@flowher thanks for this!
