### ISSUE TITLE
Remove unnecessary functions pgp_finish and pgp_crypto_finish

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#49]
These two functions don't seem used:

* `pgp_finish`
* `pgp_crypto_finish`

Let's get rid of them?

**Comment by randombit** [comment]
Were previously used because OpenSSL requires an explicit shutdown operation, but as of 2.0 Botan doesn't maintain any global state so there is nothing to cleanup. So `pgp_crypto_finish` became a noop during the conversion. Probably can be removed.

**Comment by flowher** [comment]
Closing as those functions were removed some time ago:

```
> grep -r "pgp_crypto_finish" *
> grep -r "pgp_finish" *       
>
```
