### ISSUE TITLE
Replace PKCS v1.5 code with Botan equivalent

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#50]
From @randombit :

rnp rolls its own PKCSv1.5 encoding code and then uses OpenSSL's RSA_NO_PADDING (or now Botan's equivalent "Raw"). Instead rnp should use the library version of the padding operations.

This will probably require some significant changes because rnp also wants to compute the signature digests itself, and it seems like in some cases the packet parsing code and digest update code are somewhat intertwined. 

rnp's requirement for message recovery on RSA signatures (RSA_public_decrypt in OpenSSL land) is not available through the Botan signature API. The message encryption case is probably easier to tackle.

**Comment by ronaldtse** [comment]
Thank you @randombit for handling this!

**Comment by randombit** [comment]
Done! Closing

**Comment by ronaldtse** [comment]
Thanks guys!
