### ISSUE TITLE
pgp_validate_key_sigs leaks seckey

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#501]
## Description

https://github.com/riboseinc/rnp/blob/1a8a2ab8ddc46104d83c87662b9e426d40e90623/src/librepgp/validate.c#L300

This seckey doesn't seem to be freed. I also don't see `CT_SECRET_SUBKEY` being handled here and would kind of expect it to be (haven't really looked into this).

**Comment by ni4** [comment]
`pgp_validate_key_sigs` was replaced with newer code so not an issue anymore.
