### ISSUE TITLE
ElGamal should directly use Botan instead of internal BN implementation

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#51]
From @randombit :

rnp implements ElGamal using OpenSSL's BN API, since it is not supported by OpenSSL. Botan already includes it.

**Comment by flowher** [comment]
I'll take this guy

**Comment by ronaldtse** [comment]
@flowher Thanks for volunteering! If @randombit is OK with it go for it.

**Comment by randombit** [comment]
OK with me, you should be able to use the `botan_pk_op_{encrypt,decrypt}` functions just as in `pgp_rsa_private_decrypt` and `pgp_rsa_public_encrypt`. Let me know if you run into problems.

One thing to note, ElGamal ciphertexts consist of two BIGNUM values (``g^k`` and ``msg*y^k``) and it looks like rnp/OpenPGP store these two values separately at the packet layer. Botan's ElGamal formats the two bignums together into a single byte string, so you will have to first encrypt then parse out the two values as bignums again.

**Comment by ronaldtse** [comment]
Thanks @randombit for the detailed tips. @flowher please go ahead and thank you in advance!

**Comment by flowher** [comment]
@randombit Thanks for information. Indeed I need to parse the output (and remove optional leading zeros). 
Also, for elgamal I'll need function similar to `botan_pubkey/private_load_dsa`. Can you merge it to botan if I provide the code?

**Comment by randombit** [comment]
@flowher Sorry I had missed that a way of loading the key was missing, patch most welcome.

**Comment by flowher** [comment]
@ronaldtse @randombit This is now implemented on my branch "elgamal_on_botan-conv". It is based on randombint's "botan-conv".  I need to wait until "Convert from OpenSSL to Botan for crypto operations #48" pull request is merged, before opening pull request for this.

One more thing to note - this PR depends on this commit to Botan https://github.com/randombit/botan/pull/1008, so newer version of Botan is required.

**Comment by shaunwheelhouse** [comment]
Very sorry about the delay on #48! Feel free to roceed when you're ready @flowher.

**Comment by ronaldtse** [comment]
I've updated the install instructions to use the latest Botan master since randombit/botan#1008 is now merged.

**Comment by flowher** [comment]
Great!
Thanks

**Comment by ronaldtse** [comment]
@flowher is this completed and should we close this? Thanks!

**Comment by flowher** [comment]
Done
