### ISSUE TITLE
Rename 'passphrase' things to 'password'

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#515]
## Description

https://github.com/riboseinc/rnp/issues/512 reminded me of this.

We seem to use the terms "password" and "passphrase" interchangeably in different parts of the code base (and user-facing portions).

There's arguably a difference in connotation but I think we're better off picking one and sticking to it.

As a native "U.S. English" speaker, I never really hear the term "passphrase" used outside of the context of cryptography, so I vote for using "password".

**Comment by ronaldtse** [comment]
Me too, vote for "password"!

**Comment by ni4** [comment]
Voting for 'password' too.

**Comment by ronaldtse** [comment]
@dewyatt since we have enough people agreeing, it looks like a simple "search and replace" that perhaps can be done soon? Thanks!

**Comment by ni4** [comment]
If nobody else want to take this I can do it.

**Comment by ronaldtse** [comment]
Please go ahead @ni4 !

**Comment by antonsviridenko** [comment]
To my understanding, 'passphrase' implies multiple words and therefore usually should be stronger than 'password' :)
