### ISSUE TITLE
Contribute (and move) Fast CRC implementation to Botan

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#524]
## Description

@flowher 's fast CRC implementation in #522 is faster than Botan's current implementation.

We should contribute it to Botan and use it from there.

cc: @randombit

**Comment by flowher** [comment]
Thnx. Oki do it today. I want to check first how much it cost to call botan thru ffi

**Comment by flowher** [comment]
CRC(old) rnp calling botan:
```
rnp --enarmor=msg /tmp/1gb.rnd --output  4.54s user 0.73s system 97% cpu 5.419 total
rnp --dearmor out.xxx --output out.d  5.47s user 0.78s system 96% cpu 6.490 total
```

CRC-4-byte-slicer rnp calling botan:
```
rnp --enarmor=msg /tmp/1gb.rnd --output  2.15s user 0.83s system 92% cpu 3.234 total
rnp --dearmor out.xxx --output out.d  3.32s user 0.67s system 94% cpu 4.219 total
```

CRC-4byte-slicer in RNP directly:
```
    NEW: rnp --enarmor=msg /tmp/1gb.rnd --output  2.38s user 0.86s system 79% cpu 4.089 total
    NEW: rnp --dearmor out.xxx --output out.d  3.28s user 0.84s system 96% cpu 4.275 total
```

OLD CRC in RNP directly:
```
    OLD: rnp --enarmor=msg /tmp/1gb.rnd --output  4.48s user 0.89s system 98% cpu 5.429 total
    OLD: rnp --dearmor out.xxx --output out.d  5.58s user 0.65s system 98% cpu 6.338 total
```

**Comment by flowher** [comment]
PR to botan: https://github.com/randombit/botan/pull/1280

**Comment by ronaldtse** [comment]
Already implemented in https://github.com/randombit/botan/pull/1281 and #526 . Thank you @flowher !

**Comment by ronaldtse** [comment]
Thank you @flowher and @ni4 !!
