### ISSUE TITLE
Next step in G10 format

### ISSUE THREAD

**Issue by catap** [riboseinc/rnp#536]
Hey,

It isn't a bug. It is a discussion question.

Few days ago I've started to finish implementation of missed part of G10 — `openpgp-native`.

And first step was to create an example of key.

Here I realised that GnuPG uses it only as internal protocol between `gpg-agent` and `gpg`, and I see only one way to get example of this packet — capture a traffic between them.

But here I start feeling that I'm moving at wrong direction and support internal GnuPG protocols is something that looks like an overengineering.

So, my idea that we should say that G10 is full compatibility with gpg.

Or I miss something? @dewyatt, @ronaldtse ?

**Comment by catap** [comment]
any toughts?

**Comment by ni4** [comment]
I think all depends on future usecases of rnp. If we need to communicate with gpg-agent, i.e. use GnuPG key store via the agent then we need it. If we only need to support only keys in files, databases, callbacks or other custom storages then we don't need it (or, need it as some separate callback-based code piece).

**Comment by catap** [comment]
@ni4 yes, and I don't see any points when we need communuicate with gpg-agent. Honestly it maybe a hell because gpg and gpg-agent updates at same time and it is very easy to gpg team introduce something new at gpg-agent protocol as internal release ;)

**Comment by ronaldtse** [comment]
Indeed I agree that our goal of compatibility is not within the GPG suite, but with the keys and key stores.
