### ISSUE TITLE
Some key grips are calculated incorrectly

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#540]
## Description

Key grips are not calculated correctly for all PK types.
With Elgamal keys, for example, the calculated grip does not match up with GnuPG.

I had to dig into the libgcrypt source a bit and I can see that there is a "generic" keygrip calc method that is used for certain PK types:
https://github.com/gpg/libgcrypt/blob/ce1cbe16992a7340edcf8e6576973e3508267640/cipher/pubkey.c#L669
We have not implemented the generic method, which appears to be used for elg, as can be seen here:
https://github.com/gpg/libgcrypt/blob/ce1cbe16992a7340edcf8e6576973e3508267640/cipher/elgamal.c#L1136
Note the missing keygrip computation func, compared to RSA:
https://github.com/gpg/libgcrypt/blob/ce1cbe16992a7340edcf8e6576973e3508267640/cipher/rsa.c#L1624

## Steps to Reproduce

1.` gpg --homedir=$PWD/src/tests/data/keyrings/1/ --list-keys --with-keygrip`
2. ` src/rnpkeys/rnpkeys --homedir=$PWD/src/tests/data/keyrings/1 --list-keys` (actually we don't list grips right now, so just add a hexdump call in to `rnp_key_store_add_keydata` maybe)

**Comment by dewyatt** [comment]
@catap hoping you'll have time to look! :)

**Comment by dewyatt** [comment]
(Kirill must be busy, so this is up for grabs.)

**Comment by catap** [comment]
(@dewyatt thanks, I tried to start fixing this few times, but I'm on rush :( )

**Comment by ronaldtse** [comment]
@ni4 would you have time to look into this issue? Thanks!

**Comment by ni4** [comment]
Ok, @ronaldtse!
