### ISSUE TITLE
Remove madness related to redefining BN_ functions

### ISSUE THREAD

**Issue by flowher** [riboseinc/rnp#543]
## Description

BN_bin2bn() is defined as PGPV_BN_bin2bn which wraps calls to botan... That's a heritage related to usage OpenSSL in old times.

Cleanup needed. We don't need all those #defines

**Comment by flowher** [comment]
Question here - if we remove PGPV_ prefix, then function names will be same as in OpenSSL. I wonder if this may cause problems when rnp is linked with openssl. Ideally it shouldn't as there is no reason why RNP would export BN_ functions (or at least I don't see why)

**Comment by ni4** [comment]
What about renaming functions to mpi_something, and do the same with BIGNUM type - rename it to the MPI? As in OpenPGP standard big numbers are called 'multi-precision integers'

**Comment by flowher** [comment]
Let's start with low handing fruits and remove functions which are not needed

**Comment by flowher** [comment]
And simply change all BN_xxx to bn_xxx
