### ISSUE TITLE
Support SM3 hash function using Botan implementation

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#55]
Thanks to @dewyatt (and @randombit ) we have a SM3 hash implementation merged to Botan. This task is to implement support of it in rnp within the OpenPGP framework.

**Comment by ronaldtse** [comment]
Thanks @randombit for handling this. I have to let you know that SM3 isn't currently in the OpenPGP spec (RFC4880 or RFC4880bis01). We will need to create an extension to the spec 👍

**Comment by ronaldtse** [comment]
Since we're going down this track we should also support the other Chinese requirements, SM2 (Public Key ECC), SM4 (Symmetric Cipher), by adding them into Botan and then rnp.

**Comment by randombit** [comment]
@ronaldtse For SM3 we just need to pick a value in the OpenPGP "Private/Experimental algorithm" range to identify the hash within the OpenPGP message format (range is 100 to 110 - I'm not sure if any other implementation uses any of these values, it would be nice to avoid conflicts if we can), and also create figure out what OID is used for PKCSv1.5+SM3 signatures (Botan will need to include those). I found this doc http://gmssl.org/docs/oid.html that specifies OIDs for SM3 hash as well as RSA+SM3 signatures under the OID arc reserved for the "Chinese Cryptography Standardization Technology Committee" so I guess those are probably the values to use.

There is a description in English of SM4 here http://eprint.iacr.org/2008/329.pdf
And of the SM2 algorithms here - https://tools.ietf.org/html/draft-shen-sm2-ecdsa-02

**Comment by ronaldtse** [comment]
Indeed @randombit ! GMSSL is a fork of OpenSSL that contains implementations of the SM series, and both SM2 and SM3 have been published as drafts on IETF. Therefore we could do SM2/3 now as extensions on OpenPGP given support in Botan. For the SM4 cipher we could refer to the paper and also the GMSSL implementation.

I do not know of any experimental signature/encryption schemes currently being publicly used with OpenPGP except with the now standardized extensions. I assume we have to work with the IETF PGP group to get an assignment. The GMSSL OIDs are official AFAIK.

**Comment by randombit** [comment]
Done!
