### ISSUE TITLE
RNP uses consant IV equal to 0 for symmetric encryption (CFB)

### ISSUE THREAD

**Issue by flowher** [riboseinc/rnp#554]
After quick look at symmetric ciphers, it seems to me that RNP doesn't use IV CFB encryption. Design of this mode strongly requires IV to be unpredictable in order to be secure. NIST specification 800-38A says "The  IV  need  not  be  secret,  but  it  must  be  unpredictable". It means - using constant IV is insecure.

This bug is mainly about ``init_encrypted_dst`` (``stream-write.c``), but this occures in many calls to ``pgp_cipher_start``.

**Comment by ronaldtse** [comment]
Oh dear. Lucky we have you who found it 👍 

Do we have a good random provider in our lib to use here?

**Comment by flowher** [comment]
Yup, time to implement  #251
I actually think, IV doesn't have to be unpredictable for CFB, but surely can't be constant string of 0.

**Comment by ni4** [comment]
This is not a bug, but standard compliance. Instead of random IV OpenPGP uses random bytes on the encrypted stream start.

RFC 4880, page 45:
```
   The Initial Vector (IV) is specified as all
   zeros.  Instead of using an IV, OpenPGP prefixes a string of length
   equal to the block size of the cipher plus two to the data before it
   is encrypted.  The first block-size octets (for example, 8 octets for
   a 64-bit block length) are random, and the following two octets are
   copies of the last two octets of the IV.
```

**Comment by ronaldtse** [comment]
I'm pretty sure CFB IV requires unpredictability.

**Comment by ronaldtse** [comment]
@ni4 indeed the random block contents would work.

**Comment by flowher** [comment]
@ni4, ok then, issue is a bit different. 
We don't check return value from ``pgp_random(enchdr, blsize);`` and this may fail.

**Comment by ni4** [comment]
@flowher You are right, thanks. I will add PR to fix this in a couple of minutes.

**Comment by flowher** [comment]
@ni4 I'm implementing completely different random generation, so I'm  on it.
It seems to me there are more issues  - f.e. we are using this OpenPGP CFB in ``encrypted_add_password``

**Comment by ni4** [comment]
@flowher If you are about zero-IV then this is also standard compliance:
```
   If the encrypted session key is present, the result of applying the
   S2K algorithm to the passphrase is used to decrypt just that
   encrypted session key field, using CFB mode with an IV of all zeros.
```

**Comment by dewyatt** [comment]
Yeah I feel like we had this discussion before at some point. It's strange in some places, but the spec says to do things this way.

It's good that we have eyes on these things though (keep digging!).

To expand on what @ni4 wrote above (as far as `encrypted_add_password`):

>    Note: because an all-zero IV is used for this decryption, the S2K
   specifier MUST use a salt value, either a Salted S2K or an Iterated-
   Salted S2K.  The salt value will ensure that the decryption key is
   not repeated even if the passphrase is reused.

**Comment by flowher** [comment]
I need to do more digging indeed. If in phrase "using CFB mode with an IV of all zeros", CFB means OpenPGP-CFB then I'm afraid we don't do things correctly (the first block-size octets are not random). If it means normal CFB, then I fail to see how it is secure.
Also, I'll move this OpenPGP-CFB mode to separated place (that's actually ongoing at the moment)
