### ISSUE TITLE
Remove ``grip_hash_bignum`` and use ``BN_hash`` instead

### ISSUE THREAD

**Issue by henrydcase** [riboseinc/rnp#558]
## Description

See #555 

We could replace ``grip_hash_bignum`` with ``BN_hash stuff``. Implementation of both functions does same thing, but in slidely different way.
This task requires regeneration of test data as current key rings store value of keygrip precalculated with ``grip_hash_bignum`` function

BTW: This may be related to #540  (indeed, I confirm GPG keygrips are different than RNP, but I havn't found any specification which would describe algorithm for keygrip calculation)

**Comment by ni4** [comment]
As far as I understand, keygrip is GnuPG-only thing, used to communicate keys between gpg and gpg-agent. So, as we don't use gpg-agent, I don't see much sense in supporting/implementing it (except, maybe, some g10-keyring related things). Only keyid and keyfp are parts of the standard.

**Comment by flowher** [comment]
So maybe the better idea is - let's remove this code and then we get rid of 2 problems at same time

**Comment by ni4** [comment]
I don't think that we should just remove it, but, at least, clarify usage. 
And it seems I mislooked it usage. Actualy, according to comment in code (and key grip calculation code) `keygrip is subjectKeyHash from pkcs#15`. It should be used to get key from token by it's fingerprint, and looks like GnuPG agent simulates token interface for key retrieval.
@dewyatt should know more about it

**Comment by dewyatt** [comment]
> As far as I understand, keygrip is GnuPG-only thing, used to communicate keys between gpg and gpg-agent. 

Correct, it's not part of OpenPGP. As you mentioned, it mostly seems to stem from the lib/agent separation and the G10 format. The agent's key format (G10) simply doesn't store enough information to actually calculate keyid or fpr (version, creation time, etc).

Quoting from https://github.com/gpg/gnupg/blob/774245508920eccb6a28b719a5cde26861800c60/agent/keyformat.txt#notes:

> The keygrip is a unique identifier for a key pair, it is independent of any protocol, so that the same key can be used with different protocols. PKCS-15 calls this a subjectKeyHash; it can be calculated using Libgcrypt’s gcry_pk_get_keygrip ().

> according to comment in code (and key grip calculation code) keygrip is subjectKeyHash from pkcs#15.

I'm not sure it's entirely accurate to say the keygrip is subjectKeyHash though, as it does apparently use (hash) s-exps in some cases, as mentioned in #540 (kind of a combination of PKCS#15 and SPKI?).

Anyways, removing keygrip would mean removing support for G10 entirely (the filenames in `private-keys-v1.d` are literally grip + `.key, for example`).

**Comment by flowher** [comment]
Ok, so removing is not an option. We need to fix.
But question that I have -  does value calculated by keygrip must be same as value calculated by GnuPG? What happens if it is not?

**Comment by dewyatt** [comment]
> Ok, so removing is not an option. We need to fix.
But question that I have - does value calculated by keygrip must be same as value calculated by GnuPG? What happens if it is not?

It would break interoperability with GnuPG. Like we wouldn't be able to say `rnp --homedir=/home/user/.gnupg [...]` with GPG 2.1.

Less importantly, users that actually look at the grip (like with `gpg --list-keys --with-keygrip` or `gpg --list-keys --with-colons`) would maybe be confused.

**Comment by flowher** [comment]
Thnx! 
I see - so the value should be calculated exactly same way as it's done in GnuPG.
