### ISSUE TITLE
DSA support

### ISSUE THREAD

**Issue by flowher** [riboseinc/rnp#559]
## Description

We have some code for DSA signatures, however key generation is missing. This also means that this code is not tested.
We probably should either remove this code (who uses DSA nowadays?) or if there is a usecase - add DSA keygen and tests

EDIT:
As we need to support this algorithm, then the code itself needs to be rewritten - important checks are missing, code seems to leak memory, part of DSA is implemented in bn.c and I'm not sure if what happens if user supplies "wrong" hash. I would say - this code is not usable in current form.

**Comment by ronaldtse** [comment]
@flowher very good question! I think DSA is somewhat necessary since RFC 4880 states:

> Implementations MUST implement DSA for signatures

Would you have time to add the DSA key gen and tests?

**Comment by ni4** [comment]
We definitely need to update rnpkeys with the selection of key algorithm. This was added as issue #486 
And, we cannot drop DSA support - it is still widely used (also as DSA2 with larger key sizes/hashes), is part of the standard, and we must be backwards compatible - so every old signature may be verified.

**Comment by flowher** [comment]
@ni4 thnx for link. @ronaldtse sure, I'll add it

**Comment by ronaldtse** [comment]
@flowher just to confirm you're working on this issue, if so please assign yourself. Thanks!

**Comment by flowher** [comment]
Assigned to myself, should be done next year

**Comment by ronaldtse** [comment]
Thanks @flowher, look forward to it in the new year 😉

**Comment by flowher** [comment]
Requires new FFI function in botan for DSA generation (this is done) but waiting for this
* https://github.com/randombit/botan/issues/1411

to be integrated as DSA requries strong prime and that's quite long

**Comment by randombit** [comment]
@flowher DSA uses a different param generation algorithm which is not affected by the bug.

**Comment by flowher** [comment]
Yup, found it DSA_Kosherizer.

**Comment by ronaldtse** [comment]
We can probably limit to the 3 sizes and document it? Thoughts @ni4 @dewyatt @randombit ?

**Comment by ni4** [comment]
@ronaldtse @flowher  I think that we should add ability to generate key of any size, once it is possible and documented. Maybe @randombit will tell us why botan uses more time to generate non-x1024 number of bits.

**Comment by flowher** [comment]
@ronaldtse @ni4 @randombit Actually, after double checking, botan generates DSA key with different sizes quite quickly. Need to do some debugging, but that shouldn't be a problem anymore.

**Comment by ronaldtse** [comment]
@flowher sounds good -- hope to see this issue completed soon!

**Comment by flowher** [comment]
@ronaldtse Actually, DSA is all done  - key generation of any size key added (function with possibility to generate it from expert mode), DSA signing/verif reimplemented (I don't think it was ever working), cmock tests and tests against GnuPG also there. Everything is here:
https://github.com/flowher/rnp/commits/elgamal_dsa/dsa

I'm not merging because, compilation will fail as it needs a function in botan's FFI. This is also done here (https://github.com/flowher/botan/commits/key_generation_dsa_elgamal). And I want to add it to botan when I have elgamal implemented.

Elgamal is also almost done here (https://github.com/flowher/rnp/commits/elgamal_dsa/elgamal_keygen), I just need to merge it on top of DSA.

There is one issue with GnuPG though - it seems gpg doesn't accept DSA/1024 keys which are signed with SHA256. I don't understand why, it seems to me like an issue in theirs code.

**Comment by ni4** [comment]
@flowher Does this even happen with ‘—enable-dsa2’ option? DSA is stick to 1024/SHA1 by standart so this should be the reason.

**Comment by flowher** [comment]
@ni4  I'm not sure if --enable-dsa2 is enabled, but it imports correctly all the keys above 1024 bits, so I assume it is. In fact, correctness of DSA algorithm (refereed  by rfc4880bis03) doesn't depend on hash algorithm or it's size (I know openpgp is a bit special about it).  Additionally, as per rfc4880b3, keys which have used SHA256 to generate signature must be accepted, as SHA256 must be implemented.
RNP uses SHA256 as default hash, knowing that SHA1 is insecure as of today, I like rnp doesn't use it by default.
