### ISSUE TITLE
rnpv crash

### ISSUE THREAD

**Issue by shaunwheelhouse** [riboseinc/rnp#57]
During testing I found that the rnpv utility is crashes due to an access violation caused by indexing an invalid address in the `mem` member of the `mem` `pgp_mem_t` parameter to the `rnpv/libverify.c:read_pkt` function:

```
/* mem      = 0x7fad04402880
 * mem->cc  = 0
 * mem->mem = 0xffffffffffffffff
 */
pkt.tag = mem->mem[mem->cc++];
```

It looks like this is triggered from an element in the `pgp->areas` array passed down `main` -> `pgpv_read_pubring` -> `read_binary_file` -> `read_all_packets` -> `read_pkt`. I'm not yet sure of the exact cause.

**Comment by ni4** [comment]
Since rnpv was removed from the codebase I am closing this.
