### ISSUE TITLE
make install target is broken

### ISSUE THREAD

**Issue by randombit** [riboseinc/rnp#593]
`make install` fails

```
 /bin/mkdir -p '/tmp/rnp/usr/local/include'
 /usr/bin/install -c -m 644 rnp.h rnp/rnp.h rnp/rnp_def.h rnp/rnp_sdk.h rnp/rnp_types.h rekey/rnp_key_store.h '/tmp/rnp/usr/local/include'
/usr/bin/install: will not overwrite just-created '/tmp/rnp/usr/local/include/rnp.h' with 'rnp/rnp.h'
```

Another problem here is I think the intent is `rnp/rnp_def.h` will be installed into `include/rnp` but would instead end up going to `include`

**Comment by ni4** [comment]
@randombit This doesn't seem to be an issue anymore, isn't it?

**Comment by randombit** [comment]
Works for me now, cmake conversion probably fixed this. Closing.
