### ISSUE TITLE
Support for additional curves

### ISSUE THREAD

**Issue by henrydcase** [riboseinc/rnp#615]
## Description

New draft of the standards introduces some changes with which code base should be aligned
* Curve25519
    * it is added as SHOULD but in reality it's a must have as that's a curve which probably will be used the most with ECDH
    * it was always our plan to add it anyway
* Brainpool curves
    * they are added as MAY but as those curves use short Weierstrass form, so adding them should be easy even if not supported by botan (which I believe is not a case)
* compressed point format for curves expressed in Montgomery form - we only support uncompressed format (except for EdDSA)
* test for a zero point

**Comment by henrydcase** [comment]
@ronaldtse what do you think?

**Comment by ronaldtse** [comment]
What can I say — agree with all of them :wink:
