### ISSUE TITLE
test_dsa_roundtrip test timeouts

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#629]
## Description

Continuing from https://github.com/riboseinc/rnp/pull/619#issuecomment-365655632.

I was hoping the simple solution in #625 would be OK but it looks like it can take > 10 minutes on the first key generation within that test on travis.

Anyways, I guess the simplest solutions would be:
1. Increase the timeout, or
2. Speed up/trim the test

I think @henrydcase talked about (2) before so that might be simplest. Thoughts?

## Steps to Reproduce

1. https://travis-ci.org/riboseinc/rnp/jobs/341324652#L1894

**Comment by henrydcase** [comment]
https://github.com/riboseinc/rnp/pull/630
I don't think we need to test all those combinations. Most important combinations are already tested in cli_test.py. Testing only few should be enough to prove that round trip works.  I suspect after #616 is done I'll have better idea on how to speed up DSA, so maybe then we can enable them back.

**Comment by dewyatt** [comment]
> BTW: I would be surprised if fist key generation takes 10min as it's 1024 bit key. Is it possible travis doesn't flush output?

I had the same thought, it could just not be flushing stdout and is just timing out on the 3072 like you said.

**Comment by henrydcase** [comment]
Okis, I can take care of this - have some ideas, need to try them.
