### ISSUE TITLE
Improve AEAD code and performance

### ISSUE THREAD

**Issue by ni4** [riboseinc/rnp#645]
## Description

Currently botan's FFI for AEAD uses 'granularity' and processes data in 256-512 byte chunks, which may affect performance and makes AEAD code more complicated.
Also FFI doesn't have a good way to reset cipher state without resetting the scheduled key(s).
And, internally, during key schedule, botan for AEAD does it twice with the same key data.

**Comment by henrydcase** [comment]
Re FFI: it would be good if start() does the reset - then we don't have to call reset explicitly and it's compatible with all corret uses of botan's FFI API

**Comment by randombit** [comment]
Just added `botan_cipher_reset` which allows resetting message specific state without resetting the key. Not available until it is released as part of 2.8 however so be some time before we can make use of it.

**Comment by randombit** [comment]
It appears the stream code is sending up to 32K buffers at a time to the AEAD, which is more than enough to get optimum performance. In profiling encrypting a large file with OCB mode (on AES-NI system), over 50% of the runtime is in `memcpy` (mostly in `dst_write`). So I think this can be closed.
