### ISSUE TITLE
Version bump and RPM spec

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#681]
Given the maturity level RNP is at we should bump to a 1.0 with a corresponding RPM spec update.

**Comment by dewyatt** [comment]
I have to be honest - I somehow forgot about this for a while. :worried:

I have a small unrelated PR to do for rnp but will be jumping on this after that. I may want to get an updated botan RPM for CentOS done first (need botan 2.3.0+ last I checked).

Also, just a note but personally I would feel more comfortable with 0.x releases. We still have a lot of open issues and the FFI hasn't seen much use yet so it's hard to call it mature.

Anyways, regardless of version, I'll work on getting a release done.

**Comment by ronaldtse** [comment]
Glad you found it again! We can certainly keep the 0.x moniker, as long as it is close to 1.0 😉

**Comment by ronaldtse** [comment]
@dewyatt I had to build the RPM tonight and realized that the `cmake/version.cmake` script depends on the git tags (seems that #693 is necessary).

Can you help push a `v0.9.0` tag (and remove the existing 3.99* one) for an official release? Thanks!

**Comment by ronaldtse** [comment]
I've added the `v0.9.0` tag which is necessary for RPM packaging (and removed the old 3.99.18 one).

**Comment by dewyatt** [comment]
I see you found it has to be an annotated tag (but can have an empty message). This is part of the workflow document that I'm trying to flesh out a bit more. I wasn't planning to have any tags in master, but it sounds like it's a bit late for that.

**Comment by ronaldtse** [comment]
Actually feel free to update the flow, and the tag. I was attempting to make a buildable rpm for our yum repo that our toolchain can directly publish.

**Comment by dewyatt** [comment]
This is all good now, forgot to close.
