### ISSUE TITLE
Use external JSON C library instead of libmj

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#7]
Since we haven't got enough hands on this it is preferred to utilize a well-maintained, external, JSON C library instead of the original.

**Comment by zgyarmati** [comment]
If nobody else is into this, i'm volunteering, please confirm

**Comment by ronaldtse** [comment]
@zgyarmati it's all yours. Thanks Zoltan!

**Comment by zgyarmati** [comment]
OK, thx.
Just to confirm: my first candidate is json-c (https://github.com/json-c/json-c), which is MIT license, am I right to assume that it's suitable for us?

**Comment by ronaldtse** [comment]
Indeed @zgyarmati , JSON-C looks clean and good to go.

**Comment by ronaldtse** [comment]
@zgyarmati please use the 0.12.1 version of json-c -- we will get it packaged for EPEL. Thanks!

**Comment by zgyarmati** [comment]
Yes, i use that one, and it seems there is now API change since the previous versions, so we are good with supporting 0.12 as well.

**Comment by ronaldtse** [comment]
@zgyarmati , @ribose-jeffreylau is going package up json-c 0.12.1 as a new EPEL package, so for now please use json-c 0.12.1. Thanks!
