### ISSUE TITLE
Bump patch version for #710

### ISSUE THREAD

**Issue by ribose-jeffreylau** [riboseinc/rnp#712]
## Description

Would it be possible to bump patch version for #710 ?

This would facilitate the testing of the fix (via RPM built in our toolchain, and the toolchain requires a git tag).

**Comment by dewyatt** [comment]
I actually started getting a release together last week after https://github.com/riboseinc/rnp/pull/707 but got distracted somewhere.

Anyways, I'm working on getting this done right now.

**Comment by dewyatt** [comment]
Forgot, this is done!
