### ISSUE TITLE
Rnpkeys disregards user specified option "UserId" when generating keys

### ISSUE THREAD

**Issue by MohitKumarAgniotri** [riboseinc/rnp#72]
Currently, the sample application (rnpkeys) disregards the user specified option "UserId" and always generate keys with the default user id.

Usage: `./rnpkeys --generate-key --userid=max`
expected Output: creation of new key with custom userId as specified.
Testcase: `rnpkeys_generatekey_verifyUserIdOption`

**Comment by ni4** [comment]
This doesn't seem to be an issue anymore so I close it.
