### ISSUE TITLE
Bump version to 0.9.2

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#721]
As described here: 
https://github.com/riboseinc/enmail/issues/53

0.9.1 contains some issues that are now resolved in master, which are necessary for the correct functioning of signing emails via Ruby-RNP.

@ni4 could you help us make a release 0.9.2? Thanks!

**Comment by skalee** [comment]
It's not crucial for EnMail development in any way. That said, releasing EnMail when no compatible RNP stable release exists sounds like an unfortunate idea.

**Comment by ni4** [comment]
Yeah, I just pushed the PR #723 so once it is approved I can bump the version.

**Comment by ronaldtse** [comment]
@ni4 could we bump the version since #723 is merged? Thanks!

**Comment by ni4** [comment]
@ronaldtse Yep, will do this today.

**Comment by ronaldtse** [comment]
@ni4 and we need to tag the version here, right?

**Comment by ni4** [comment]
@ronaldtse Yeah, done as of now. So closing this.
