### ISSUE TITLE
validate_pgp_key_signature doesn't fail when it should

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#726]
## Description

Lots of assigning to `res` in various places:
https://github.com/riboseinc/rnp/blob/dff813481ad9925749ec57faa7a8752c47aa8e5b/src/librepgp/stream-key.cpp#L1314

But it's never used:
https://github.com/riboseinc/rnp/blob/dff813481ad9925749ec57faa7a8752c47aa8e5b/src/librepgp/stream-key.cpp#L1335

@ni4 can you take a look?

**Comment by ni4** [comment]
@dewyatt Thanks for pointing at this. I'll take a look.
