### ISSUE TITLE
Support exporting a public key from a secret key (ffi)

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#734]
## Description

It would be good to support extracting a public key from a secret key for `rnp_key_export`.

**Comment by ni4** [comment]
I can do this together with other stuff I'm working on right now.

**Comment by ronaldtse** [comment]
Hello @ni4 any updates to this issue? Thanks!

**Comment by ni4** [comment]
@ronaldtse I got stuck with #722 at some point, but now got back, and plan to finish it very soon. Then will be able to get to public key export.

**Comment by ronaldtse** [comment]
@ni4 any updates so far? Thanks!

**Comment by ni4** [comment]
@ronaldtse I finished with the code and now writing tests and so on. This will go in PR together with solution for #722

**Comment by dewyatt** [comment]
This is done I think.
