### ISSUE TITLE
Unable to directly load subkeys

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#737]
## Description

1bc81b31d1563598f98ee91e009256ea0631ae93 broke one of ruby-rnp's examples (which unfortunately I never added to CI).

## Steps to Reproduce

```
cd /tmp

git clone https://github.com/riboseinc/rnp
pushd rnp
git checkout 1bc81b31d1563598f98ee91e009256ea0631ae93
# bad - 1bc81b31d1563598f98ee91e009256ea0631ae93
# good - fa896f54ad96cfb8ad7efea19b217ab27a3b0ff1
cmake -DBUILD_SHARED_LIBS=on . && make -j8
popd

git clone https://github.com/riboseinc/ruby-rnp
cd ruby-rnp
bundle install
env LD_LIBRARY_PATH=$PWD/../rnp/src/lib bundle exec ruby examples/key_provider.rb
```

## Use Case

The [example in question](https://github.com/riboseinc/ruby-rnp/blob/fbf0f30224790603f88ed9fedf6660f6efcb3ad1/examples/key_provider.rb) would previously function like so:
1. Receive some (subkey)-encrypted data from an unknown source.
2. Ask rnp to decrypt it.
3. Rnp would request this subkey (via keyid) from the key provider (within the ruby example).
4. The example's key provider would check its "database" (folder) for this keyid, and provide this key to rnp.
5. Rnp would recognize that this is a subkey and request the primary.
6. The example would then repeat the process and provide the primary.
7. Then, once rnp has both the primary and sub, it would decrypt the data.

**Comment by ronaldtse** [comment]
@dewyatt any updates here? Thanks!

**Comment by ni4** [comment]
@ronaldtse I hope to fix this in code I'm working on right now.

**Comment by ni4** [comment]
@dewyatt I got to this issue, and it seems to be a bit controversial. Ruby example calls FFI code `rnp_load_keys`, which then calls `rnp_key_store_load_from_mem`. This one tries to load keys from OpenPGP key format, which should include public/secret key and then all the sigs, userids, subkeys and so on.
Should I change the behavior in the way that it will also accept subkey?  Logically subkeys should be bounded to the main key.

**Comment by dewyatt** [comment]
@ni4 I understand what you mean, but I'm not sure I view it as controversial necessarily. The OpenPGP spec doesn't really dictate how keys are stored, it just provides the transferable key as a baseline for interoperability with other implementations. G10 is valid for example, though it does not appear in the spec, because the implementation can still generate a transferable key from it.

I do agree that it's logical that you should not be able to load a subkey without providing the primary.

The issue in the ruby example is that it feels like too much burden on the application to maintain a link between every primary keyid and every subkey keyid.

Previous behavior:
1. App receives some subkey-encrypted OpenPGP data.
2. App asks rnp to decrypt it.
3. rnp requests the subkey (by keyid) from the app.
4. App provides the subkey.
5. rnp determines that it is a subkey, requests the primary (by keyid) from the app.
6. App provides the primary.
7. Primary+sub have been loaded, decryption can proceed.

Current behavior:
1. App receives some subkey-encrypted OpenPGP data.
2. App asks rnp to decrypt it.
3. rnp requests the subkey (by keyid) from the app.
4. App has to somehow determine the primary keyid from the subkey keyid, and provide the primary+sub.
[...]

It's this last step that feels burdensome to me.

So again, I do agree that we should not support loading an orphan subkey (I don't think we ever supported this). But I think the old behavior described above did make some sense. It does the same thing, only in more steps, and removes the requirement that an application store a mapping of every primary-keyid to every subkey-keyid.

It's just my .02, and may be worth discussing further.

**Comment by ni4** [comment]
@dewyatt Agree that previous behavior makes a lot of sense. Implementation, which uses FFI, should not care about keyids and primary keys/subkeys. 
What about extending the FFI api with function `rnp_load_key` (or  `rnp_add_key`?), which will be aware that we have path to single key file and use different approach in loading? 
Other possible way is to add flag, like `RNP_LOAD_SAVE_SINGLE_KEY`, to `rnp_load_keys`.

**Comment by dewyatt** [comment]
My initial thought is that it's a bit strange to treat this as a special case. We had this functioning previously via `rnp_load_keys`, what are the issues preventing that now?

It seems like it could be treated similar to merging in additional signatures:
1. `rnp_load_keys` on ring1.gpg, which contains primary key 07E69D4C38247878 and subkey E501C048F86EB3E3.
2. `rnp_load_keys` on ring2.gpg, which also contains keys 07E69D4C38247878+E501C048F86EB3E3, and some additional signatures on that key/id.
3. The additional signatures are merged in, everything else remains unchanged.

Similarly:
1. `rnp_load_keys` on ring1.gpg, which contains primary key 07E69D4C38247878 and subkey E501C048F86EB3E3.
2. `rnp_load_keys` on ring2.gpg, which also contains keys 07E69D4C38247878+E501C048F86EB3E3, and a new subkey 7D456E68914EB7A4
3. The additional signatures are merged in, everything else remains unchanged.

**Comment by ni4** [comment]
@dewyatt Ah, sure. Changing key files in the way that each subkey is saved with the main key before it will work. I'll update ruby-rnp example to store subkeys in this way.

**Comment by dewyatt** [comment]
@ni4 Actually I misspoke on that, I meant that I'd prefer we support the existing example. Requiring the primary key to be duplicated with every subkey seems similarly burdensome as the keyid issue discussed above. If the application can provide the primary key when requested, I can't see any reason that every subkey must be stored with it (except when interacting with other OpenPGP implementations).
