### ISSUE TITLE
`fgets` waits for keystroke when asking for password

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#75]
Reported by @MohitKumarAgniotri : I was able to make the test cases use the pass-fd, but apparently for some reason the call to read the password (i.e. fgets() ) waits for a keystroke to continue.

**Comment by MohitKumarAgniotri** [comment]
This is NOT an issue as I encountered it due to my own fault. 
The reason stems from the fact that I was passing the filename instead of a file descriptor and it was making it fail. 
@ronaldtse: Please close this issue as a reject.

**Comment by ronaldtse** [comment]
Thanks @MohitKumarAgniotri !
