### ISSUE TITLE
Consider taking code from libEncryptMsg

### ISSUE THREAD

**Issue by evpo** [riboseinc/rnp#755]
## Consider taking code from libEncryptMsg

Now that you are moving to C++ you could analyse if the symmetric encryption code I wrote for [EncryptPad](https://github.com/evpo/EncryptPad)  can be reused. Since version 0.4.0.0 (released in January 2018), I extracted everything for OpenPGP to a separate independent library [libEncryptPad](https://github.com/evpo/libencryptmsg). It's been thoroughly tested and included in production version of EncryptPad since January.

## What you can get from the library?

1. All packets related to symmetrical encryption
2. Streaming functionality (memory to memory, file to file).
3. The API is very similar to Botan standards. @randombit should like it :)
4. Unit tests
5. Small project production quality

## What you cannot get from the library?

1. Packets and functionality for asymmetrical encryption. However, the library was written with future asymmetrical functionality in mind.
2. Documentation is minimal

## License

Seems to be compatible: Simplified BSD License.

## Dependencies

Link to the list: https://www.evpo.net/libencryptmsg/#acknowledgments

## My thoughts

I looked at rnp current code. It seems to be at the beginning of C - C++ transformation. I don't know what your plans are. If you want to leave it as is and write C++ code around it, you don't need to go ahead with libEncryptMsg. Otherwise, if your plan is to write everything with C++ design in mind, it can be useful. Anyway, my goal is to let you know about this option. I am happy to help and I might even contribute in the future.

**Comment by ronaldtse** [comment]
At this point, our code is stable, heavily tested, excels at demanding workloads, with top-of-line performance, minimal memory usage, and supports OpenPGP extensions not available elsewhere. 

Perhaps you could promote your library to projects that are less mature. Thank you for the note.

**Comment by evpo** [comment]
Thanks for your reply. I thought there was a chance that you would rewrite the pieces that were previously C according to C++ design guidelines listed in [CPP_USAGE](https://github.com/riboseinc/rnp/blob/master/doc/CPP_USAGE.md).

**Comment by evpo** [comment]
I read my text again. I think it looks as if I am promoting my library for some reason but it wasn't my intent. I wanted to contribute the code as a contributor. Then I would have stopped maintaining libEncryptMsg and build EncryptPad against RNP. libEncryptMsg would be consumed by RNP and disappear. The promotion style of my text was to emphasize that  the code I wanted to contribute was stable to some extent.
