### ISSUE TITLE
Refactoring : resolve_userid

### ISSUE THREAD

**Issue by MohitKumarAgniotri** [riboseinc/rnp#78]
Function `resolve_userid` should be refactored to do only what is specified/implied by the function name.
Currently, function `resolve_userid` does two things:
- Queries the RNP structure to find the Value for UserId
- Finds the key from the keyring (`pgp_getkeybyname`) using the derived Userid

**Comment by ni4** [comment]
This was resolved as a part of PR #258. So I'm closing it now.
