### ISSUE TITLE
Remove redundant key listing code from rnpkeys

### ISSUE THREAD

**Issue by ni4** [riboseinc/rnp#791]
## Description

Currently we have the following key listing commands:
- `rnpkeys --list-keys [keyid/userid/other search string]`. It lists key(s) in the following format:
```
pub   2048/RSA (Encrypt or Sign) 5d20c3e12382ef48 2017-08-15 [SC]
      f49500d98f5165bc02e05b875d20c3e12382ef48
uid           testkey@rsa
sub   2048/RSA (Encrypt or Sign) e83d3905c8459f04 2017-08-15 [E]
      91e8ca0a6fcfd3a097a1c1b5e83d3905c8459f04
```

- `rnpkeys --list-sigs 5d20c3e12382ef48`. It works as the previous but adds sigs (only certification ones):
```
pub   2048/RSA (Encrypt or Sign) 5d20c3e12382ef48 2017-08-15 [SC]
      f49500d98f5165bc02e05b875d20c3e12382ef48
uid           testkey@rsa
sig           5d20c3e12382ef48 2017-08-15 testkey@rsa
sub   2048/RSA (Encrypt or Sign) e83d3905c8459f04 2017-08-15 [E]
      91e8ca0a6fcfd3a097a1c1b5e83d3905c8459f04
```

- `rnpkeys --get-key 5d20c3e12382ef48`. It displays key in the almost the same format as first one:
```
signature 2048/RSA (Encrypt or Sign) 5d20c3e12382ef48 2017-08-15 [SC] 
                 f495 00d9 8f51 65bc 02e0 5b87 5d20 c3e1 2382 ef48 
uid              testkey@rsa
```

- `rnpkeys --format mr --get-key 5d20c3e12382ef48`. Uses different format:
```
pub:f49500d98f5165bc02e05b875d20c3e12382ef48:1:2048:1502791214:0
uid:1502791214:0:testkey@rsa
```

- `rnpkeys --trusted-keys 5d20c3e12382ef48`. Doesn't work without parameter, and with parameter displays the following key info (which doesn't do anything about trust):
```
key=f49500d98f5165bc02e05b875d20c3e12382ef48
name=testkey@rsa
creation=1502791214
expiry=0
version=4
alg=1
n=c6cb4b0ccab3bbb3119aa383b92893508cd2dff35f4e1921c3d2747e7f0b7e46587e91162bdee0ea2fa3446771862e30d102e20b14db531bc1be2b5a36327cbc4ad3d7c02ac602ee473073650adeff005776d1dbca34745123057f5948282fc45b4849e6eb96d46142dd66c7291d30431703104300aebb6d5606b821274b95c2225606f1ae5dcbd6acacf05b2c877f85c96cb0c7a125cd5cbc4678e29eec9d55d01cf42f8747ff3f95d032a97281cd7ead1f9532b24c7f5e1489ed05f27629aca64725916d9e32f0cb34c6a3e6fca559d7df9e443f06a35bc49519d104e23a27ed446de6ba2ecf6f22172c30d00f0ae295965683abcb457df903062b66b17771
e=010001
```

That's too much, I think we should leave only one command `--list-keys`, with two specifiers - `--with-sigs` and `--json`. Later we could add some more specifiers to display more key details.

@dewyatt @ronaldtse What do you think?

**Comment by dewyatt** [comment]
Definitely in need of some consolidation and cleanup, good idea!
