### ISSUE TITLE
FFI: Implement non-JSON key generation interface

### ISSUE THREAD

**Issue by ni4** [riboseinc/rnp#796]
## Description

While we have interface to generate keys, using the JSON format, it is not well usable from low-level languages which doesn't handle JSON natively (like Ruby does).
So it would be good to have function-based interface as well.

## Suggested interface

Following functions are  proposed to implement the same level of functionality which JSON interface has right now (should be subject for discussion):

``` C
rnp_result_t rnp_key_generate_create(rnp_ffi_t ffi, rnp_key_generate_handle_t *handle, const char *alg);

rnp_result_t rnp_subkey_generate_create(rnp_key_generate_handle_t primary, rnp_key_generate_handle_t *handle, const char *alg);

rnp_result_t rnp_key_generate_set_bits(rnp_key_generate_handle_t key, size_t bits);

rnp_result_t rnp_key_generate_set_hash(rnp_key_generate_handle_t key, const char *hash);

rnp_result_t rnp_key_generate_set_dsa_qbits(rnp_key_generate_handle_t key, size_t qbits);

rnp_result_t rnp_key_generate_set_curve(rnp_key_generate_handle_t key, const char *curve);

rnp_result_t rnp_key_generate_set_protection_cipher(rnp_key_generate_handle_t key, const char *cipher);

rnp_result_t rnp_key_generate_set_protection_hash(rnp_key_generate_handle_t key, const char *hash);

rnp_result_t rnp_key_generate_set_protection_mode(rnp_key_generate_handle_t key, const char *mode);

rnp_result_t rnp_key_generate_set_protection_iterations(rnp_key_generate_handle_t key, size_t iterations);

rnp_result_t rnp_key_generate_add_usage(rnp_key_generate_handle_t key, const char *usage);

rnp_result_t rnp_key_generate_remove_usage(rnp_key_generate_handle_t key, const char *usage);

rnp_result_t rnp_key_generate_set_userid(rnp_key_generate_handle_t key, const char *userid);

rnp_result_t rnp_key_generate_set_expiration(rnp_key_generate_handle_t key, uint32_t expiration);

rnp_result_t rnp_key_generate_clear_pref_hashes(rnp_key_generate_handle_t key);

rnp_result_t rnp_key_generate_add_pref_hash(rnp_key_generate_handle_t key, const char *hash);

rnp_result_t rnp_key_generate_clear_pref_compression(rnp_key_generate_handle_t key);

rnp_result_t rnp_key_generate_add_pref_compression(rnp_key_generate_handle_t key, const char *compression);

rnp_result_t rnp_key_generate_clear_pref_ciphers(rnp_key_generate_handle_t key);

rnp_result_t rnp_key_generate_add_pref_cipher(rnp_key_generate_handle_t key, const char *cipher);

rnp_result_t rnp_key_generate_set_pref_keyserver(rnp_key_generate_handle_t key, const char *keyserver);

rnp_result_t rnp_generate_key(rnp_key_generate_handle_t key, rnp_key_generate_handle_t subkey);

rnp_result_t rnp_key_generate_get_key(rnp_key_generate_handle_t genkey, rnp_key_handle_t *key);

rnp_result_t rnp_key_generate_handle_destroy(rnp_key_generate_handle_t *key);

```

**Comment by ni4** [comment]
@dewyatt @ronaldtse What do you think about it?

**Comment by dewyatt** [comment]
I think it's a good idea! I would say that ideally one implementation will just use the other implementation internally. So, probably the JSON implementation could be modified to just use this API you've proposed here, so we don't have two full implementations.

**Comment by ni4** [comment]
@dewyatt Yeah, that's what I wanted to do - no reason to have duplicate code.

**Comment by dewyatt** [comment]
I do think we could improve on this API as far as being consistent with the rest of the FFI operations:
* function names should be like `rnp_op_generate_*`
* types should be `rnp_op_generate_t` (currently `handle` is only used when referring to keys, not operations), `rnp_op_generate_st`
* operations should have an `execute` and `destroy`
* operation `_create` functions always take the operation output pointer as the first param
* operation `_create` functions always take an `rnp_ffi_t` as the second param

So I would expect something more like:
```c++
rnp_result_t rnp_op_generate_create(
    rnp_op_generate_t *op,
    rnp_ffi_t        ffi,
    const char *alg
);
rnp_result_t rnp_op_generate_subkey_create(
    rnp_op_generate_t *op,
    rnp_ffi_t        ffi,
    rnp_key_handle_t primary,
    const char *alg
);
```
(Also, I think the subkey generation `create` func should probably take a key handle as shown here).

IIRC to match the JSON key generation API, it needs to support:
* primary only generation
* subkey only generation (adding a subkey to an existing primary)
* primary+subkey generation

**Comment by ni4** [comment]
@dewyatt Thanks for the input! First I started with the same `rnp_op_generate` but then got stuck with distinguishing key/subkey parameters setup. However rnp_op_generate_subkey_create() pointing on the existing primary key solves that problem. So basically users will need first generate primary key (or obtain it in other way), and then just build and call rnp_op_generate() another time to add the subkey.

**Comment by ni4** [comment]
> Right that's what I was thinking, so I guess the one thing it wouldn't support that the JSON API does is the "primary+subkey" generation, which doesn't seem like an issue when you can just do it separately.

Given that (most likely) 95% of users will generate keys with default parameters, choosing only key algorithm/bits(curve), and userid, we may add some functions like `rnp_generate_rsa(ffi, bits, subbits, userid)`, `rnp_generate_dsa_eg(ffi, bits, subbits, userid)`, `rnp_generate_ecdh(ffi, curve, userid)`, `rnp_generate_25519(ffi, userid)` to make things easier for them.
