### ISSUE TITLE
test_forged_key_validate, test_stream_key_signature_validate, and test_cli_g10_operations tests fail

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#797]
## Description

These 3 tests are failing for me locally. I suspect it passed CI because we had an older cached version of deps (incl. botan). I cleared the cache in travis and re-ran our most recent master and indeed they fail.

## Steps to Reproduce

1. https://travis-ci.org/riboseinc/rnp/builds/485233154 (re-ran this)

@ni4 Can you take a look?

**Comment by ni4** [comment]
@dewyatt Sure, I'll take a look. Thanks for noticing.

**Comment by ni4** [comment]
@dewyatt Looks like some test keys were set to expire in a year, after Jan, 28. Will make a PR with fixes a bit later.

**Comment by dewyatt** [comment]
@ni4 That makes sense, thanks!
