### ISSUE TITLE
Replace OpenSSL dependency with the Botan cryptographic library

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#8]
OpenSSL while used ubiquitously, it comes with the burden that it is version locked due to its status of a system library.

We'd like to replace it with the [Botan](http://botan.randombit.net) library, which supports a number of algorithms we wish to work with.

**Comment by ronaldtse** [comment]
@randombit thank you for the work! The OpenSSL dependency is indeed completely gone but there are a few remaining textual references to OpenSSL (below), and the usage of `USE_BN_INTERFACE` (looks temporary) remains.

Could you help clean them up so we'll close this issue? Thanks!

``` bash
src/cmocka/rnp_tests.c:46:  #include <openssl/bn.h>
src/lib/bn.c:37:/* OpenSSL BIGNUM emulation layer */
src/lib/crypto.h:280:int openssl_read_pem_seckey(const char *, pgp_key_t *, const char *, int);
src/lib/librnp.3:167:The library uses functions from the openssl library for multi-precision
src/lib/pem.c:89:openssl_read_pem_seckey(const char *f, pgp_key_t *key, const char *type, int verbose)
src/lib/ssh2pgp.c:378:  if (!openssl_read_pem_seckey(f, key, "ssh-rsa", 0)) {
src/lib/ssh2pgp.c:392:          /* openssh and openssl have p and q swapped */
src/cmocka/rnp_tests.c:#if defined(USE_BN_INTERFACE)
src/lib/bn.h:#define USE_BN_INTERFACE
src/lib/bn.h:#ifdef USE_BN_INTERFACE
src/lib/bn.h:#endif /* USE_BN_INTERFACE */
```

**Comment by randombit** [comment]
@ronaldtse No problem PR coming shortly
