### ISSUE TITLE
RNP is dramatically slow in Docker, under some circumstances

### ISSUE THREAD

**Issue by skalee** [riboseinc/rnp#805]
## Description

I was hunting for some EnMail's spontaneous build failures in Travis CI (which are unlikely to be related to RNP). For this reason, I've crafted a Dockerfile which resembles Travis to some degree. However, I've noticed that in this environment RNP is terribly slow whereas GnuPG is blazing fast (at least on my computer). Hence, I'm creating this issue to let you know. Perhaps there is something to investigate performance-wise, or maybe some optional dependency should be described in README as "highly recommended". I am not sure whether this issue is related to RNP or its Ruby bindings.

## Steps to Reproduce

I've prepared a Dockerfile, which builds RNP and GnuPG on top of Ubuntu Xenial, fetches EnMail, and runs its test suite. Only required dependencies are installed. Test results are followed by a performance report, which clearly displays that RNP is slower than GnuPG several dozen times.

Following snippet builds a Docker image, and runs it:

```
docker build -f Dramatically-Bad-Performance.dockerfile . -t slow
docker run -t slow
```

The dockerfile and the output of test performance measurement (printed by running that docker image) are in this gist: https://gist.github.com/skalee/febbb43a76c4c17eb95aa23f002691d4.

**Comment by ronaldtse** [comment]
It's interesting to see that the fastest spec running RNP is at over 6 seconds:

```
  EnMail::Adapters::RNP#sign_and_encrypt_string uses specific algorithm for signature computation
    6.71 seconds ./spec/unit/adapters/rnp_spec.rb:103
```

I wonder if this has to do the with limited entropy inside a Docker container -- are the specs generating any keys? Limited entropy will affect the speed of key generation.

**Comment by skalee** [comment]
In this unit test for adapter, RNP library is mocked. This is why. ;) Only these which start with `./spec/acceptance` are certainly not mocked nor stubbed.

**Comment by skalee** [comment]
Interesting thing is that in this particular unit test whole cryptography is mocked. However, key lookup is not.

**Comment by dewyatt** [comment]
99.99% of this is because we don't cache validated key signatures (I thought we had an open issue for this, but can't find it), which GnuPG does.
If you comment out the below lines you'll find we're much closer:
https://github.com/riboseinc/rnp/blob/eeda91bd39af5bde0e9866e7f7d9ea8007c5602f/src/librekey/rnp_key_store.cpp#L597
https://github.com/riboseinc/rnp/blob/eeda91bd39af5bde0e9866e7f7d9ea8007c5602f/src/librekey/rnp_key_store.cpp#L606

**Comment by skalee** [comment]
I guess this one can be closed, unless you want to create an issue related to caching first?

**Comment by ronaldtse** [comment]
@dewyatt in this case can we have a new issue on caching validating key signatures?

The list here: 
https://gist.github.com/dewyatt/878c5ae1fa087a2dd648c8a5f8a09366 gives us a good indication on which areas we should improve on too!

**Comment by dewyatt** [comment]
@ronaldtse Yes, definitely. I thought we had one filed but I'm not seeing it, so I filed a new one.

And thanks for the great performance data @skalee !
