### ISSUE TITLE
redumper crashes

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#813]
## Description

I noticed `redumper` crashes here:
https://github.com/riboseinc/rnp/blob/786529d18ff5a6ae94640a3d0e9266147a7ac088/src/apps/packet-dumper/redumper.cpp#L77-L78

I'm not familiar with the history of this workaround, but it looks like it would always crash:
https://github.com/riboseinc/rnp/blob/786529d18ff5a6ae94640a3d0e9266147a7ac088/src/librepgp/stream-ctx.cpp#L34-L36

(We don't do any testing of `redumper` so it's easy for this to go unnoticed)

## Steps to Reproduce

1. `src/apps/packet-dumper/redumper somefile.gpg`

**Comment by ni4** [comment]
Thanks, @dewyatt . Just got accross this, will fix it.
