### ISSUE TITLE
Infinite loop on truncated armored key

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#824]
## Description

I noticed this today and realized it makes for a pretty simple DoS vector.

## Steps to Reproduce

1. `curl -LO https://gist.githubusercontent.com/dewyatt/85d2c2e730480164addd91a4fc915a19/raw/814976e1c2dbb239802c51deb0d8a458f55db700/partial-key.asc`
2. `rnpkeys --import partial-key.asc`

## Expected Behavior

It should fail to import and exit.

## Actual Behavior

100% CPU usage, some infinite loop somewhere, no exit.

**Comment by ronaldtse** [comment]
Wow, ought to fix this. Thanks for finding this out @dewyatt !

**Comment by ni4** [comment]
@dewyatt Thanks for finding this! I'll take care of this issue.
