### ISSUE TITLE
test_cli_g10_operations failing

### ISSUE THREAD

**Issue by kaie** [riboseinc/rnp#882]
I get this test failure on a debian buster system. This is with a local build of the tip of botan.

2: [ RUN      ] test_cli_g10_operations
2: [signature_calculate() /home/user/github/rnp/src/lib/crypto/signatures.cpp:113] Signature and secret key do not agree on algorithm type
2: [signed_dst_finish() /home/user/github/rnp/src/librepgp/stream-write.cpp:1146] failed to calculate signature
2: [process_stream_sequence() /home/user/github/rnp/src/librepgp/stream-write.cpp:1737] failed to finish stream
2: [rnp_protect_file() /home/user/github/rnp/src/rnp/rnpcli.cpp:1139] failed with error code 0x10000002
2: [  ERROR   ] --- 0x1 != 0
2: [   LINE   ] --- /home/user/github/rnp/src/tests/cli.cpp:241: error: Failure!
2: [  FAILED  ] test_cli_g10_operations

**Comment by dewyatt** [comment]
I'm not able to reproduce this. :(

```sh
docker run -ti --rm debian:buster bash -l
apt update
apt -y install git cmake make g++ libbz2-dev zlib1g-dev libcmocka-dev libjson-c-dev python gnupg pkg-config

git clone --depth 1 https://github.com/randombit/botan.git
cd botan
./configure.py
make -j8 install

# regular user from here on
useradd -m daniel
su -l daniel

git clone --depth 1 https://github.com/riboseinc/rnp.git
cd rnp
mkdir build
cd build
cmake ..
make -j8
ctest -V -R rnp_tests
```

```
100% tests passed, 0 tests failed out of 2

Total Test time (real) =  80.05 sec
```

Can you provide more information? An exact sequence of commands, whether this is a container/VM/phys, etc.

**Comment by kaie** [comment]
I'll try to figure out what's different in my system compared, it's in my dev VM.

**Comment by kaie** [comment]
Is it necessary to build and install botan as root?

In my setup, I'm installing it as a regular user.
I could reproduce the problem on my system, with a new, clean user account.
I didn't use docker.

Using the following commands, I can still reproduce the failure.

Either it's "didn't install botan as root", or something else is different on my system. However, I'm not aware of any global modification as root, besides installing packages.

I can try what happens in a fresh VM on my system.

usedadd -m user2
su - user2

git clone --depth 1 https://github.com/randombit/botan.git
cd botan
./configure.py --prefix=/home/user2/local
make install

cd   # back to home dir

git clone --depth 1 https://github.com/riboseinc/rnp.git
cd rnp
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/home/user2/local/ ..
make
ctest -V -R rnp_tests

**Comment by dewyatt** [comment]
I tried again in a fresh container and installed botan as a regular user, all tests still pass for me.
Can you provide the output (maybe in a gist) of:

```
dpkg -l
uname -a
```

I *have* seen this issue before, but have never been able to reproduce it. @ni4 @ronaldtse are either of you able to repro?

**Comment by kaie** [comment]
I cannot reproduce it in a fresh AWS/EC2 instance! Installed from a debian 9 image, upgrade to debian 10, built, and test passed.

I reproduced it again in a fresh VM on my local system.

Note my local host runs the Qubes OS, and I'm running a debian 10 guest "qube" inside it. The Qubes distributors probably made some tweaks to make it compatible with the host OS, but I never experience any kind of failure on my system, have been running it for almost a year.

Problem happened with 4 CPUs and 10 GB RAM, and also with 2 CPUs and 4 GB RAM.

CPU, uname and package list uploaded here:
https://kuix.de/misc/rnp-issue-882-debian10-packages.txt

**Comment by ni4** [comment]
@dewyatt @kaie While I didn't see such issue before, and I mostly run all stuff natively on macOS, i have a guess that it is related to the issue #458 
The test tries signing with default g10 secret key, and if due to some technical reasons non-signing key (or subkey) comes first, then it will be picked up as default. 
@kaie Could you please do `ls -la src/tests/data/test_stream_key_load/g10` on failing system?

**Comment by kaie** [comment]
@ni4 Output from a failing and a working system:

https://kuix.de/misc/rnp-822-qubes-vm-failing.txt

https://kuix.de/misc/rnp-822-aws-ec2-host-working.txt

**Comment by kaie** [comment]
I executed the following commands on both systems:
```
echo hello > /tmp/hello.txt
./src/rnp/rnp --home src/tests/data/test_stream_key_load/g10 --sign /tmp/hello.txt
```

On both systems I get:
```
Enter password for key 0x6e2f73008f8b8d6e:
```

**Comment by ni4** [comment]
@kaie Thanks! Unfortunately missed that `ls` will sort file name, while our g10 loading code relies on readdir() order (which doesn't do any sorting and return files in system-dependent order).
That's actually what happens with the key `0x6e2f73008f8b8d6e` : it is RSA subkey, with filename `A5E4CD2CBBE44A16E4D6EC05C2E3C3A599DC763C.key`.
I reproduced behavior you have by deleting few `.key` files till got hit with encrypt-only algorithm of the key.
To make sure that it's the same case could you please build code from the branch https://github.com/riboseinc/rnp/tree/ni4-reproduce-g10-error ? It will print some additional debug info and tell which key is picked as default.

And the solution would in fixing the issue #458

**Comment by kaie** [comment]
> To make sure that it's the same case could you please build code from the branch https://github.com/riboseinc/rnp/tree/ni4-reproduce-g10-error ? It will print some additional debug info and tell which key is picked as default.

see https://kuix.de/misc/rnp-822-repro.txt

**Comment by ni4** [comment]
@kaie Yeah, it's the same case - rnp picks up 256-bit ECDH subkey as the default key, and tries to use it for signing. Will fix it soon, thanks for bringing this up!

**Comment by kaie** [comment]
Thanks for your help.
