### ISSUE TITLE
Tests stalling

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#91]
The rnp_tests are stalling out and failing.
The reason is that `pass-fd` is interpreted as a decimal value (`atoi`) but we are storing a hexadecimal value there.
@MohitKumarAgniotri Can you replace the last parameter in all the calls to convert() with 10? That should fix that.

Can you also change `numbits = 1024` in all the tests as it's much faster to run and should certainly not have an effect on the validity of the tests.

**Comment by MohitKumarAgniotri** [comment]
@dewyatt : will do.

**Comment by MohitKumarAgniotri** [comment]
@dewyatt done! :+1:
